---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question. 
---
= Forum aux questions sur la classification BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette FAQ peut vous aider si vous cherchez juste une réponse rapide à une question.



== Service de classification BlueXP

Les questions suivantes présentent des généralités sur la classification BlueXP.



=== Qu'est-ce que la classification BlueXP ?

La classification BlueXP est une offre cloud qui utilise la technologie basée sur l'intelligence artificielle (IA) pour vous aider à comprendre le contexte des données et à identifier les données sensibles dans vos systèmes de stockage. Les systèmes peuvent être des environnements de travail que vous avez ajoutés à BlueXP Canvas et de nombreux types de sources de données auxquels la classification BlueXP peut accéder via vos réseaux. link:faq-cloud-compliance.html#what-sources-of-data-can-be-scanned-with-bluexp-classification["Voir la liste complète ci-dessous"].

La classification BlueXP fournit des paramètres prédéfinis (tels que les types et catégories d'informations sensibles) pour répondre aux nouvelles réglementations de conformité en matière de confidentialité et de sensibilité des données, notamment le RGPD, la CCPA et l'HIPAA.



=== Fonctionnement de la classification BlueXP

La classification BlueXP déploie une autre couche d'intelligence artificielle en parallèle avec votre système et vos systèmes de stockage BlueXP. Il analyse ensuite les données sur des volumes, des compartiments, des bases de données, ainsi que d'autres comptes de stockage, et indexe les informations exploitables concernant les données. La classification BlueXP exploite à la fois l'intelligence artificielle et le traitement du langage naturel, contrairement aux autres solutions généralement construites autour d'expressions régulières et de la mise en correspondance de modèles.

La classification BlueXP utilise l'IA pour fournir une compréhension contextuelle des données pour une détection et une classification précises. Elle est axée sur l'IA, car elle est conçue pour répondre aux besoins de types et d'évolutivité des données modernes. Il comprend également le contexte des données afin d'assurer une découverte et une classification solides et précises.

link:concept-cloud-compliance.html["Découvrez le fonctionnement de la classification BlueXP"^].

https://bluexp.netapp.com/netapp-cloud-data-sense["En savoir plus sur les utilisations de la classification BlueXP"^].



=== Qu'en est-il de l'architecture de la classification BlueXP ?

La classification BlueXP déploie un serveur ou un cluster unique, où que vous soyez, dans le cloud ou sur site. Les serveurs se connectent via des protocoles standard aux sources de données et indexent les résultats dans un cluster Elasticsearch, qui est également déployé sur les mêmes serveurs. Cette prise en charge permet la prise en charge d'environnements multicloud, interclouds, clouds privés et sur site.



=== Quels sont les fournisseurs de cloud pris en charge ?

La classification BlueXP fonctionne avec BlueXP et prend en charge AWS, Azure et GCP. Votre entreprise peut ainsi bénéficier d'une visibilité unifiée sur la confidentialité des données entre les différents fournisseurs de cloud.



=== La classification BlueXP utilise-t-elle une API REST et des outils tiers ?

Non, la classification BlueXP ne dispose pas d'API REST.



=== La classification BlueXP est-elle disponible sur les marchés ?

Oui, la classification BlueXP et BlueXP est disponible sur les marchés AWS, Azure et GCP.



== Analyse de classification et analytique BlueXP

Les questions suivantes se rapportent aux performances de l'analyse de classification BlueXP et aux analyses disponibles pour les utilisateurs.



=== À quelle fréquence la classification BlueXP analyse-t-elle mes données ?

L'analyse initiale de vos données peut prendre un peu de temps, mais les analyses suivantes ne permettent qu'd'examiner les modifications incrémentielles, ce qui réduit les temps d'analyse du système. La classification BlueXP analyse vos données de manière continue selon une séquence périodique, six référentiels à la fois, de sorte que toutes les données modifiées soient classifiées très rapidement.

link:concept-cloud-compliance.html#how-scans-work["Découvrez le fonctionnement des acquisitions"].

Notez que la classification BlueXP analyse les bases de données une seule fois par jour. Les bases de données ne sont pas continuellement analysées comme d'autres sources de données.

L'analyse des données a un impact négligeable sur vos systèmes de stockage et sur vos données. Toutefois, si vous êtes préoccupé, même par un très faible impact, vous pouvez configurer la classification BlueXP pour effectuer des analyses « lentes ». link:task-reduce-scan-speed.html["Découvrez comment réduire la vitesse de numérisation"].



=== Puis-je effectuer des recherches dans mes données à l'aide de la classification BlueXP ?

Les fonctionnalités de recherche étendues de la classification BlueXP facilitent la recherche d'un fichier ou d'un élément de données spécifique dans l'ensemble des sources connectées. La classification BlueXP permet aux utilisateurs d'effectuer des recherches plus approfondies que les métadonnées ne reflètent. Il s'agit d'un service indépendant de la langue qui peut également lire les fichiers et analyser une multitude de types de données sensibles, tels que les noms et les ID. Par exemple, les utilisateurs peuvent effectuer des recherches dans des magasins de données structurés et non structurées pour trouver des données qui peuvent s'être divulguées des bases de données aux fichiers des utilisateurs, en violation de la stratégie de l'entreprise. Les recherches peuvent être enregistrées ultérieurement et des règles peuvent être créées pour rechercher et prendre des mesures sur les résultats à une fréquence définie.

Une fois les fichiers qui vous intéressent trouvés, les caractéristiques peuvent être listées, y compris les balises, le compte de l'environnement de travail, le compartiment, le chemin du fichier, catégorie (à partir de la classification), taille du fichier, dernière modification, statut d'autorisation, doublons, niveau de sensibilité, données personnelles, types de données sensibles dans le fichier, propriétaire, type de fichier, taille de fichier, heure de création, hachage de fichier, si les données ont été attribuées à une personne demandant son attention, et plus encore. Les filtres peuvent être appliqués aux caractéristiques de tramage qui ne sont pas pertinentes. La classification BlueXP dispose également de contrôles RBAC pour permettre le déplacement ou la suppression de fichiers si les autorisations appropriées sont présentes. Si les autorisations appropriées ne sont pas présentes, les tâches peuvent être affectées à une personne de l'entreprise qui dispose des autorisations appropriées.



=== La classification BlueXP propose-t-elle des rapports ?

Oui. Les informations offertes par la classification BlueXP peuvent être pertinentes pour les autres parties prenantes de votre entreprise. Nous vous aidons à générer des rapports pour partager les informations exploitables. Les rapports suivants sont disponibles pour la classification BlueXP :

Rapport d'évaluation des risques pour la confidentialité:: Fournit des informations sur la confidentialité à partir de vos données et un score de risque lié à la confidentialité. link:task-generating-compliance-reports.html#privacy-risk-assessment-report["En savoir plus >>"^].
Rapport de demande d'accès au sujet des données:: Vous permet d'extraire un rapport de tous les fichiers contenant des informations concernant le nom spécifique ou l'identifiant personnel d'un sujet de données. link:task-generating-compliance-reports.html#what-is-a-data-subject-access-request["En savoir plus >>"^].
Rapport PCI DSS:: Vous aide à identifier la distribution des informations de carte de crédit dans vos dossiers. link:task-generating-compliance-reports.html#pci-dss-report["En savoir plus >>"^].
Rapport HIPAA:: Vous aide à identifier la distribution de l'information sur la santé dans vos dossiers. link:task-generating-compliance-reports.html#hipaa-report["En savoir plus >>"^].
Rapport de mappage de données:: Fournit des informations sur la taille et le nombre de fichiers dans vos environnements de travail. Cela inclut la capacité d'utilisation, l'âge des données, la taille des données et les types de fichiers. link:task-controlling-governance-data.html#data-mapping-report["En savoir plus >>"^].
Rapport d'évaluation de la découverte des données:: Fournit une analyse de haut niveau de l'environnement analysé afin de mettre en évidence les résultats du système et de montrer les points préoccupants et les étapes de correction potentielles. link:task-controlling-governance-data.html#data-discovery-assessment-report["Mode apprentissage"^].
Rapports sur un type d'information spécifique:: Des rapports sont disponibles, incluant des détails sur les fichiers identifiés qui contiennent des données personnelles et des données personnelles sensibles. Vous pouvez également voir les fichiers dérépartis par catégorie et par type de fichier. link:task-controlling-private-data.html["En savoir plus >>"^].




=== Les performances d'acquisition varient-t-elles ?

Les performances de l'analyse peuvent varier en fonction de la bande passante réseau et de la taille moyenne des fichiers dans votre environnement. Elle peut également dépendre des caractéristiques de taille du système hôte (dans le cloud ou sur site). Voir link:concept-cloud-compliance.html#the-bluexp-classification-instance["Instance de classification BlueXP"^] et link:task-deploy-cloud-compliance.html["Classification BlueXP : déploiement"^] pour en savoir plus.

Lors de l'ajout initial de nouvelles sources de données, vous pouvez également choisir d'effectuer uniquement une analyse de « mappage » au lieu d'une analyse de « classification » complète. Le mappage peut être effectué très rapidement sur vos sources de données car il n'accède pas aux fichiers pour voir les données à l'intérieur. link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["Voir la différence entre une acquisition de cartographie et une acquisition de classification"^].



== Gestion de la classification et confidentialité BlueXP

Les questions suivantes expliquent comment gérer les paramètres de classification et de confidentialité BlueXP.



=== Comment activer la classification BlueXP ?

Vous devez tout d'abord déployer une instance de classification BlueXP dans BlueXP ou dans un système sur site. Une fois l'instance en cours d'exécution, vous pouvez activer le service sur les environnements de travail, les bases de données et d'autres sources de données existants à partir de l'onglet *Configuration* ou en sélectionnant un environnement de travail spécifique.

link:task-getting-started-compliance.html["Découvrez comment démarrer"^].


NOTE: L'activation de la classification BlueXP sur une source de données entraîne une analyse initiale immédiate. Les résultats de l'analyse s'affichent peu de temps après.



=== Comment désactiver la classification BlueXP ?

Vous pouvez désactiver la classification BlueXP pour empêcher l'analyse d'un environnement de travail, d'une base de données ou d'un groupe de partage de fichiers individuels à partir de la page Configuration de la classification BlueXP.

link:task-managing-compliance.html["En savoir plus >>"^].


NOTE: Pour supprimer complètement l'instance de classification BlueXP, vous pouvez supprimer manuellement l'instance de classification BlueXP du portail de votre fournisseur cloud ou de l'emplacement sur site.



=== Puis-je personnaliser le service en fonction des besoins de mon entreprise ?

La classification BlueXP fournit des informations exploitables sur vos données. Ces informations peuvent être extraites et utilisées en fonction des besoins de votre entreprise.

En outre, la classification BlueXP offre de nombreuses façons d'ajouter une liste personnalisée de « données personnelles » que la classification BlueXP identifiera lors des analyses, ce qui vous donne une vue d'ensemble de l'emplacement des données potentiellement sensibles dans _tous_ les fichiers de votre entreprise.

* Vous pouvez ajouter des identificateurs uniques basés sur des colonnes spécifiques dans les bases de données que vous scannez -- nous appelons cela *Data Fusion*.
* Vous pouvez ajouter des mots-clés personnalisés à partir d'un fichier texte.
* Vous pouvez ajouter des répétitions personnalisées à l'aide d'une expression régulière (regex).


link:task-managing-data-fusion.html["En savoir plus >>"^].



=== Puis-je demander au service d'exclure les données d'analyse de certains répertoires ?

Oui. Si vous souhaitez que la classification BlueXP exclut les données d'analyse qui résident dans certains répertoires de sources de données, vous pouvez fournir cette liste au moteur de classification. Une fois cette modification appliquée, la classification BlueXP exclut les données d'analyse des répertoires spécifiés.

link:task-exclude-scan-paths.html["En savoir plus >>"^].



=== Les copies Snapshot résidant sur les volumes ONTAP sont-elles analysées ?

Non La classification BlueXP ne analyse pas les snapshots, car le contenu est identique au contenu du volume.



=== Que se passe-t-il si le Tiering des données est activé sur vos volumes ONTAP ?

Lorsque la classification BlueXP analyse les volumes pour lesquels les données inactives sont envoyées vers le stockage objet, il analyse toutes les données, c'est-à-dire les données qui se trouvent sur des disques locaux et les données inactives envoyées vers le stockage objet. C'est également le cas pour les produits non-NetApp qui implémentent la hiérarchisation.

L'analyse ne chauffe pas les données inactives, elles restent inactives et restent dans le stockage objet.



== Types de systèmes source et de types de données

Les questions suivantes se rapportent aux types de stockage pouvant être analysés et aux types de données analysées.



=== Quelles sources de données peuvent être analysées avec la classification BlueXP ?

La classification BlueXP peut analyser les données à partir des environnements de travail que vous avez ajoutés à BlueXP Canvas et de nombreux types de sources de données structurées et non structurées auxquels la classification BlueXP peut accéder sur vos réseaux.

Voir link:concept-cloud-compliance.html["Environnements de travail et sources de données pris en charge"].



=== Y a-t-il des restrictions lorsqu'elles sont déployées dans une région gouvernementale?

La classification BlueXP est prise en charge lorsque le connecteur est déployé dans une région gouvernementale (AWS GovCloud, Azure Gov ou Azure DoD), également appelée « mode restreint ». Lorsqu'il est déployé de cette manière, la classification BlueXP présente les restrictions suivantes :

[]
====
*REMARQUE* ces informations ne concernent que les versions 1.30 et antérieures de l'héritage de classification BlueXP.

====
* Les comptes OneDrive, les comptes SharePoint et Google Drive ne peuvent pas être analysés.
* Impossible d'intégrer la fonctionnalité de label Microsoft Azure information protection (AIP).




=== Quelles sources de données puis-je analyser si j'installe la classification BlueXP dans un site sans accès à Internet ?

La classification BlueXP ne peut analyser les données qu'à partir de sources de données locales. À ce stade, la classification BlueXP peut analyser les sources de données locales suivantes en « mode privé », également appelé site « invisible » :

* Systèmes ONTAP sur site
* Schémas de base de données
* Stockage objet qui utilise le protocole simple Storage Service (S3)


Voir link:concept-cloud-compliance.html["Environnements de travail et sources de données pris en charge"].



=== Quels types de fichiers sont pris en charge ?

La classification BlueXP analyse tous les fichiers pour rechercher des informations par catégorie et par métadonnées, et affiche tous les types de fichiers dans la section types de fichiers du tableau de bord.

Lorsque la classification BlueXP détecte des informations à caractère personnel (PII) ou lorsqu'elle effectue une recherche DSAR, seuls les formats de fichier suivants sont pris en charge :

`+.CSV, .DCM, .DICOM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== Quels types de données et de métadonnées sont capturés par la classification BlueXP ?

La classification BlueXP vous permet d'exécuter une analyse générale du « mappage » ou une analyse complète de la « classification » de vos sources de données. La cartographie ne fournit qu'une vue d'ensemble de haut niveau de vos données, tandis que Classification permet une analyse approfondie de vos données. Le mappage peut être effectué très rapidement sur vos sources de données car il n'accède pas aux fichiers pour voir les données à l'intérieur.

* Acquisition de mappage de données.
+
La classification BlueXP analyse uniquement les métadonnées. Ce qui est utile pour la gestion et la gouvernance globales des données, la définition rapide des projets, les gros domaines et la définition des priorités. Le mappage de données est basé sur les métadonnées et est considéré comme une acquisition *FAST*.

+
Après une acquisition rapide, vous pouvez générer un rapport de mappage de données. Ce rapport présente les données stockées dans vos sources de données d'entreprise et vous aide à prendre les bonnes décisions en matière d'utilisation des ressources, de migration, de sauvegarde, de sécurité et de conformité.

* Analyse de classification des données (approfondie).
+
La classification BlueXP s'analyse à l'aide de protocoles standard et d'autorisations en lecture seule dans l'ensemble de vos environnements. Les fichiers sélectionnés sont ouverts et analysés afin de détecter toute donnée sensible concernant l'entreprise, des informations privées et des problèmes liés aux attaques par ransomware.

+
Après une analyse complète, vous pouvez appliquer de nombreuses fonctionnalités de classification BlueXP supplémentaires à vos données, telles que l'affichage et le raffinage des données dans la page Data Investigation, la recherche de noms dans les fichiers, la copie, le déplacement et la suppression des fichiers source, etc.



La classification BlueXP capture des métadonnées telles que le nom du fichier, les autorisations, l'heure de création, le dernier accès et la dernière modification. Cela inclut toutes les métadonnées qui apparaissent dans la page Détails de l'investigation de données et dans les rapports d'investigation de données.

La classification BlueXP permet d'identifier de nombreux types de données privées, telles que les données personnelles et les données personnelles sensibles. Pour plus d'informations sur les données privées, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Catégories de données privées analysés par le système de classification BlueXP"].



=== Puis-je limiter les informations de classification BlueXP à des utilisateurs spécifiques ?

Oui, la classification BlueXP est entièrement intégrée avec BlueXP. Les utilisateurs de BlueXP ne peuvent voir que les informations pour les environnements de travail qu'ils peuvent afficher en fonction de leurs privilèges d'espace de travail.

En outre, si vous souhaitez permettre à certains utilisateurs d'afficher simplement les résultats de l'analyse de classification BlueXP sans pouvoir gérer les paramètres de classification BlueXP, vous pouvez attribuer à ces utilisateurs le rôle Cloud Compliance Viewer.

link:concept-cloud-compliance.html#user-access-to-compliance-information["En savoir plus >>"^].



=== Est-il possible d'accéder aux données privées envoyées entre mon navigateur et la classification BlueXP ?

Non Les données privées envoyées entre votre navigateur et l'instance de classification BlueXP sont sécurisées via un chiffrement de bout en bout avec TLS 1.2. Ainsi, NetApp et les tiers ne peuvent pas les lire. La classification BlueXP ne partage aucune donnée ou résultat avec NetApp que si vous demandez et approuvez l'accès.

Les données analysées restent dans votre environnement.



=== Comment les données sensibles sont-elles gérées ?

NetApp n'a pas accès aux données sensibles et ne les affiche pas dans l'interface utilisateur. Les données sensibles sont masquées. Par exemple, les quatre derniers chiffres sont affichés pour les informations de carte de crédit.



=== Où sont stockées les données ?

Les résultats d'analyse sont stockés dans Elasticsearch dans votre instance de classification BlueXP.



=== Comment accéder aux données ?

La classification BlueXP accède aux données stockées dans Elasticsearch via des appels API qui exigent une authentification et chiffrées à l'aide de AES-128. L'accès à Elasticsearch nécessite directement un accès racine.



== Licences et coût

La question suivante concerne les licences et les coûts d'utilisation de la classification BlueXP.



=== Combien coûte la classification BlueXP ?

La classification BlueXP est une fonctionnalité clé de BlueXP qui n'est pas facturée.



== Déploiement de connecteurs

Les questions suivantes concernent le connecteur BlueXP.



=== Quel est le connecteur ?

Il s'agit d'un logiciel exécuté sur une instance de calcul dans votre compte cloud ou sur site, permettant ainsi à BlueXP de gérer les ressources cloud de manière sécurisée. Vous devez déployer un connecteur pour utiliser la classification BlueXP.



=== Où le connecteur doit-il être installé ?

* Lorsque vous analysez les données dans Cloud Volumes ONTAP dans AWS ou Amazon FSX pour ONTAP, vous utilisez un connecteur dans AWS.
* Pour analyser les données dans Cloud Volumes ONTAP dans Azure ou dans Azure NetApp Files, vous utilisez un connecteur dans Azure.
* Pour l'analyse des données dans Cloud Volumes ONTAP dans GCP, vous utilisez un connecteur dans GCP.
* Lors de l'analyse des données dans des systèmes ONTAP sur site, des partages de fichiers NetApp ou des bases de données, vous pouvez utiliser un connecteur dans l'un de ces emplacements cloud.


Donc, si vous disposez de données à plusieurs de ces emplacements, vous devrez peut-être les utiliser https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["Plusieurs connecteurs"^].



=== La classification BlueXP requiert-elle l'accès aux identifiants ?

La classification BlueXP elle-même ne récupère pas les identifiants du stockage. Elles sont plutôt stockées dans le connecteur BlueXP.

La classification BlueXP utilise les identifiants du plan de données, par exemple les identifiants CIFS pour monter les partages avant l'analyse.



=== Puis-je déployer le connecteur sur mon propre hôte ?

Oui. C'est possible https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Déployez le connecteur sur site"^] Sur un hôte Linux de votre réseau ou sur un hôte du cloud. Si vous prévoyez de déployer la classification BlueXP sur site, vous pouvez également installer le connecteur sur site, mais ce n'est pas obligatoire.



=== La communication entre le service et le connecteur utilise-t-elle HTTP ?

Oui, la classification BlueXP communique avec le connecteur BlueXP via HTTP.



=== Qu'en est-il des sites sécurisés sans accès à Internet ?

Oui, cela est également pris en charge. C'est possible https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Déployez le connecteur sur un hôte Linux sur site qui ne dispose pas d'un accès Internet"^]. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Il s'agit également du « mode privé »"^]. Vous pourrez ensuite détecter les clusters ONTAP sur site et d'autres sources de données locales, puis analyser les données à l'aide de la classification BlueXP.



== Le déploiement de la classification BlueXP

Les questions suivantes concernent l'instance de classification BlueXP séparée.



=== Quels modèles de déploiement la classification BlueXP prend-elle en charge ?

BlueXP permet à l'utilisateur d'effectuer des analyses et des rapports sur des systèmes pratiquement n'importe où, y compris sur site, dans le cloud et dans les environnements hybrides. La classification BlueXP est généralement déployée à l'aide d'un modèle SaaS, dans lequel le service est activé via l'interface BlueXP et ne nécessite aucune installation matérielle ou logicielle. Même en ce mode de déploiement cliquer-exécuter, il est possible de gérer les données, que les datastores soient sur site ou dans le cloud public.



=== Quel type d'instance ou de machine virtuelle est requis pour la classification BlueXP ?

Quand link:task-deploy-cloud-compliance.html["déploiement dans le cloud"]:

* Dans AWS, le classement BlueXP s'exécute sur une instance m6i.4xlarge avec un disque GP2 de 500 Gio. Vous pouvez sélectionner un type d'instance plus petit pendant le déploiement.
* Dans Azure, la classification BlueXP s'exécute sur une VM Standard_D16s_v3 avec un disque de 500 Gio.
* Dans GCP, la classification BlueXP s'exécute sur une machine virtuelle n2-standard-16 avec un disque persistant standard de 500 Gio.


Notez que vous pouvez déployer la classification BlueXP sur un système avec moins de processeurs et moins de RAM, mais que l'utilisation de ces systèmes est limitée. Voir link:concept-cloud-compliance.html#using-a-smaller-instance-type["Utilisation d'un type d'instance plus petit"] pour plus d'informations.

link:concept-cloud-compliance.html["Découvrez le fonctionnement de la classification BlueXP"^].



=== Puis-je déployer la classification BlueXP sur mon propre hôte ?

Oui. Vous pouvez installer le logiciel de classification BlueXP sur un hôte Linux disposant d'un accès Internet sur votre réseau ou dans le cloud. Tout fonctionne de la même façon et vous continuez à gérer votre configuration de numérisation et vos résultats via BlueXP. Voir link:task-deploy-compliance-onprem.html["Déploiement de la classification BlueXP sur site"] pour connaître la configuration système requise et les détails de l'installation.



=== Qu'en est-il des sites sécurisés sans accès à Internet ?

Oui, cela est également pris en charge. C'est possible link:task-deploy-compliance-dark-site.html["Déployez la classification BlueXP sur un site qui ne dispose pas d'un accès Internet"] pour des sites totalement sécurisés.
