---
settings:
  name: BlueXP classification
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents de classification BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/reference-limitations.html"
  - title: Commencez
    entries:
    - title: Découvrez la classification BlueXP
      url: "/concept-cloud-compliance.html"
    - title: Déployez la classification BlueXP
      entries:
      - title: Déployez dans le cloud à l'aide de BlueXP
        url: "/task-deploy-cloud-compliance.html"
      - title: Installez sur un hôte Linux avec accès à Internet
        url: "/task-deploy-compliance-onprem.html"
      - title: Installation sur site sans accès à Internet
        url: "/task-deploy-compliance-dark-site.html"
      - title: Vérifiez que votre hôte Linux est prêt à installer la classification
          BlueXP
        url: "/task-test-linux-system.html"
    - title: Activez la numérisation sur vos sources de données
      entries:
      - title: Cloud Volumes ONTAP et ONTAP sur site
        url: "/task-getting-started-compliance.html"
      - title: Azure NetApp Files
        url: "/task-scanning-anf.html"
      - title: Amazon FSX pour ONTAP
        url: "/task-scanning-fsx.html"
      - title: Compartiments Amazon S3
        url: "/task-scanning-s3.html"
      - title: Schémas de base de données
        url: "/task-scanning-databases.html"
      - title: Comptes OneDrive
        url: "/task-scanning-onedrive.html"
      - title: Comptes SharePoint
        url: "/task-scanning-sharepoint.html"
      - title: Comptes Google Drive
        url: "/task-scanning-google-drive.html"
      - title: Partages de fichiers
        url: "/task-scanning-file-shares.html"
      - title: Stockage objet
        url: "/task-scanning-object-storage.html"
    - title: Intégrer Active Directory
      url: "/task-add-active-directory-datasense.html"
    - title: Configuration des licences
      url: "/task-licensing-datasense.html"
    - title: FAQ
      url: "/faq-cloud-compliance.html"
  - title: Utilisez la classification BlueXP
    entries:
    - title: Afficher les détails de gouvernance de vos données
      url: "/task-controlling-governance-data.html"
    - title: Affichez les détails de conformité de vos données
      url: "/task-controlling-private-data.html"
    - title: Catégories de données privées
      url: "/reference-private-data-categories.html"
    - title: Examiner vos données
      url: "/task-investigate-data.html"
    - title: Organisez vos données privées
      url: "/task-org-private-data.html"
    - title: Attribuez des règles à vos données
      url: "/task-using-policies.html"
    - title: Gérez vos données privées
      url: "/task-managing-highlights.html"
    - title: Contrôlez et gérez les événements d'accès aux fichiers
      url: "/task-manage-file-access-events.html"
    - title: Modifier les paramètres de numérisation
      url: task-managing-repo-scanning.html
    - title: Générer des rapports de conformité
      url: "/task-generating-compliance-reports.html"
  - title: Gérer la classification BlueXP
    entries:
    - title: Ajoutez des identifiants de données personnels personnalisés
      url: "/task-managing-data-fusion.html"
    - title: Afficher l'état des actions de classification BlueXP
      url: "/task-view-compliance-actions.html"
    - title: Définir les ID de groupe existants comme « ouverts à l'organisation »
      url: "/task-add-group-id-as-open.html"
    - title: Vérifiez l'historique des actions de classification BlueXP
      url: "/task-audit-data-sense-actions.html"
    - title: Réduisez la vitesse d'analyse de la classification BlueXP
      url: "/task-reduce-scan-speed.html"
    - title: Supprimez les sources de données de la classification BlueXP
      url: "/task-managing-compliance.html"
    - title: Désinstallez la classification BlueXP
      url: "/task-uninstall-data-sense.html"
  - title: Référence
    entries:
    - title: Types d'instances de classification BlueXP pris en charge
      url: "/reference-instance-types.html"
    - title: Métadonnées collectées à partir des sources de données
      url: "/reference-collected-metadata.html"
    - title: API de classification BlueXP
      url: "/api-classification.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
