---
settings:
  name: BlueXP classification
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents de classification BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/reference-limitations.html"
  - title: Commencez
    entries:
    - title: Découvrez la classification BlueXP
      url: "/concept-cloud-compliance.html"
    - title: Déployez la classification BlueXP
      entries:
      - title: Déployez dans le cloud à l'aide de BlueXP
        url: "/task-deploy-cloud-compliance.html"
      - title: Installez sur un hôte Linux avec accès à Internet
        url: "/task-deploy-compliance-onprem.html"
      - title: Installation sur site sans accès à Internet
        url: "/task-deploy-compliance-dark-site.html"
      - title: Vérifiez que votre hôte Linux est prêt à installer la classification
          BlueXP
        url: "/task-test-linux-system.html"
    - title: Activez la numérisation sur vos sources de données
      entries:
      - title: Cloud Volumes ONTAP et ONTAP sur site
        url: "/task-getting-started-compliance.html"
      - title: Azure NetApp Files
        url: "/task-scanning-anf.html"
      - title: Amazon FSX pour ONTAP
        url: "/task-scanning-fsx.html"
      - title: Compartiments Amazon S3
        url: "/task-scanning-s3.html"
      - title: Schémas de base de données
        url: "/task-scanning-databases.html"
      - title: Comptes OneDrive
        url: "/task-scanning-onedrive.html"
      - title: Comptes SharePoint
        url: "/task-scanning-sharepoint.html"
      - title: Comptes Google Drive
        url: "/task-scanning-google-drive.html"
      - title: Partages de fichiers
        url: "/task-scanning-file-shares.html"
      - title: Stockage objet
        url: "/task-scanning-object-storage.html"
    - title: Intégrer Active Directory
      url: "/task-add-active-directory-datasense.html"
    - title: Configuration des licences
      url: "/task-licensing-datasense.html"
    - title: FAQ
      url: "/faq-cloud-compliance.html"
  - title: Utilisez la classification BlueXP
    entries:
    - title: Afficher les détails de gouvernance de vos données
      url: "/task-controlling-governance-data.html"
    - title: Affichez les détails de conformité de vos données
      url: "/task-controlling-private-data.html"
    - title: Catégories de données privées
      url: "/reference-private-data-categories.html"
    - title: Examiner vos données
      url: "/task-investigate-data.html"
    - title: Organisez vos données privées
      url: "/task-org-private-data.html"
    - title: Attribuez des règles à vos données
      url: "/task-using-policies.html"
    - title: Gérez vos données privées
      url: "/task-managing-highlights.html"
    - title: Contrôlez et gérez les événements d'accès aux fichiers
      url: "/task-manage-file-access-events.html"
    - title: Modifier les paramètres de numérisation
      url: task-managing-repo-scanning.html
    - title: Générer des rapports de conformité
      url: "/task-generating-compliance-reports.html"
  - title: Gérer la classification BlueXP
    entries:
    - title: Ajoutez des identifiants de données personnels personnalisés
      url: "/task-managing-data-fusion.html"
    - title: Afficher l'état des actions de classification BlueXP
      url: "/task-view-compliance-actions.html"
    - title: Vérifiez l'historique des actions de classification BlueXP
      url: "/task-audit-data-sense-actions.html"
    - title: Réduisez la vitesse d'analyse de la classification BlueXP
      url: "/task-reduce-scan-speed.html"
    - title: Supprimez les sources de données de la classification BlueXP
      url: "/task-managing-compliance.html"
    - title: Désinstallez la classification BlueXP
      url: "/task-uninstall-data-sense.html"
  - title: Référence
    entries:
    - title: Types d'instances de classification BlueXP pris en charge
      url: "/reference-instance-types.html"
    - title: Métadonnées collectées à partir des sources de données
      url: "/reference-collected-metadata.html"
    - title: API de classification BlueXP
      url: "/api-classification.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrez la classification BlueXP
      url: concept-cloud-compliance.html
    - title: Nouveautés
      url: whats-new.html
    - title: Déployez la classification BlueXP dans le cloud à l'aide de BlueXP
      url: task-deploy-cloud-compliance.html
    - title: Installez la classification BlueXP sur un hôte Linux avec Internet
      url: task-deploy-compliance-onprem.html
    - title: Installez la classification BlueXP sur site sans Internet
      url: task-deploy-compliance-dark-site.html
    - title: Intégrer Active Directory
      url: task-add-active-directory-datasense.html
    - title: Configuration des licences
      url: task-licensing-datasense.html
  - title: Analysez vos environnements de travail
    links:
    - title: Volumes Cloud Volumes ONTAP
      url: task-getting-started-compliance.html
    - title: Volumes ONTAP sur site
      url: task-getting-started-compliance.html
    - title: Volumes Azure NetApp Files
      url: task-scanning-anf.html
    - title: Amazon FSX pour volumes ONTAP
      url: task-scanning-fsx.html
    - title: Compartiments Amazon S3
      url: task-scanning-s3.html
  - title: Analyser d'autres sources de données
    links:
    - title: Compartiments S3 génériques
      url: task-scanning-object-storage.html
    - title: Partages de fichiers non NetApp
      url: task-scanning-file-shares.html
    - title: Schémas de base de données
      url: task-scanning-databases.html
    - title: Comptes OneDrive
      url: task-scanning-onedrive.html
    - title: Comptes SharePoint
      url: task-scanning-sharepoint.html
    - title: Comptes Google Drive
      url: task-scanning-google-drive.html
  - title: Afficher les détails de vos données
    links:
    - title: Afficher les fichiers contenant des informations privées
      url: task-controlling-private-data.html
    - title: Afficher les fichiers dupliqués dans votre espace de stockage
      url: task-investigate-data.html#checking-for-duplicate-files-in-your-storage-systems
    - title: Filtrez vos données pour afficher des fichiers spécifiques
      url: task-investigate-data.html
    - title: Créez des règles pour afficher vos meilleures recherches
      url: task-using-policies.html
    - title: Générer des rapports de conformité
      url: task-generating-compliance-reports.html
  - title: Organisez vos données privées
    links:
    - title: Appliquez des balises et des propriétaires aux fichiers qui nécessitent
        une attention particulière
      url: task-org-private-data.html#applying-tags-to-manage-your-scanned-files
    - title: Catégoriser vos données à l'aide d'étiquettes AIP
      url: task-org-private-data.html#categorizing-your-data-using-aip-labels
    - title: Ajoutez vos propres identifiants de données personnels personnalisés
      url: task-managing-data-fusion.html
  - title: Gérez vos données privées
    links:
    - title: Copier les fichiers source
      url: task-managing-highlights.html#copying-source-files
    - title: Déplacer les fichiers source
      url: task-managing-highlights.html#moving-source-files-to-an-nfs-share
    - title: Supprimer les fichiers source
      url: task-managing-highlights.html#deleting-source-files
    - title: Créez des alertes par e-mail lorsque des données non conformes sont trouvées
      url: task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found
    - title: Contrôlez et gérez les événements d'accès aux fichiers
      url: task-manage-file-access-events.html
    - title: Répondre à une demande d'accès à un sujet de données
      url: task-generating-compliance-reports.html#searching-for-data-subjects-and-downloading-reports
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: Utilisations de la classification BlueXP
      url: https://bluexp.netapp.com/netapp-cloud-data-sense
    - title: Vidéos sur la classification BlueXP
      url: https://youtube.com/playlist?list=PLdXI3bZJEw7m0dFDhu3w6Yqt71Zqyl2Pw
    - title: Blog BlueXP
      url: https://bluexp.netapp.com/blog
    - title: Webinaires BlueXP
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Toute la documentation BlueXP
