---
settings:
  name: BlueXP classification
  internal:
    pdf_enabled: true
    termcheck_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents de classification BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/reference-limitations.html"
  - title: Commencez
    entries:
    - title: Découvrez la classification BlueXP
      url: "/concept-cloud-compliance.html"
    - title: Accéder à la BlueXP classification
      url: "/task-access.html"
    - title: Déployez la classification BlueXP
      entries:
      - title: Quel déploiement devez-vous utiliser
        url: "/task-deploy-overview.html"
      - title: Déployez dans le cloud à l'aide de BlueXP
        url: "/task-deploy-cloud-compliance.html"
      - title: Installez sur un hôte Linux avec accès à Internet
        url: "/task-deploy-compliance-onprem.html"
      - title: Installez sur un hôte Linux sur site sans accès à Internet
        url: "/task-deploy-compliance-dark-site.html"
      - title: Vérifiez que votre hôte Linux est prêt à installer la classification
          BlueXP
        url: "/task-test-linux-system.html"
    - title: Activez la numérisation sur vos sources de données
      entries:
      - title: Analyse de vos sources de données
        url: "/task-scanning-overview.html"
      - title: Azure NetApp Files
        url: "/task-scanning-anf.html"
      - title: Amazon FSX pour ONTAP
        url: "/task-scanning-fsx.html"
      - title: Cloud Volumes ONTAP et ONTAP sur site
        url: "/task-getting-started-compliance.html"
      - title: Schémas de base de données
        url: "/task-scanning-databases.html"
      - title: Partages de fichiers
        url: "/task-scanning-file-shares.html"
      - title: StorageGRID
        url: "/task-scanning-storagegrid.html"
    - title: Intégrer Active Directory
      url: "/task-add-active-directory-datasense.html"
  - title: Utilisez la classification BlueXP
    entries:
    - title: Afficher les détails de gouvernance de vos données
      url: "/task-controlling-governance-data.html"
    - title: Affichez les détails de conformité de vos données
      url: "/task-controlling-private-data.html"
    - title: Catégories de données privées
      url: "/reference-private-data-categories.html"
    - title: Créer une numérisation personnalisée
      url: "/task-custom-classification.html"
    - title: Examiner vos données
      url: "/task-investigate-data.html"
    - title: Créer une recherche enregistrée
      url: "/task-using-policies.html"
    - title: Modifier les paramètres de numérisation
      url: "/task-managing-repo-scanning.html"
    - title: Générer des rapports de conformité
      url: "/task-generating-compliance-reports.html"
  - title: Gérer la classification BlueXP
    entries:
    - title: Exclure les répertoires de l'analyse
      url: "/task-exclude-scan-paths.html"
    - title: Définir les ID de groupe existants comme « ouverts à l'organisation »
      url: "/task-add-group-id-as-open.html"
    - title: Supprimez les sources de données de la classification BlueXP
      url: "/task-managing-compliance.html"
    - title: Désinstallez la classification BlueXP
      url: "/task-uninstall-data-sense.html"
  - title: Fonctionnalités obsolètes
    entries:
    - title: Liste des fonctions obsolètes
      url: "/reference-free-paid.html"
    - title: Déployez les dérecommandations de classification BlueXP
      entries:
      - title: Installez la classification BlueXP sur plusieurs hôtes sans accès Internet
        url: "/task-deploy-multi-host-install-dark-site.html"
    - title: Dépercations des données d'acquisition
      entries:
      - title: Analyse des compartiments Amazon S3
        url: "/task-scanning-s3.html"
      - title: Analysez les comptes OneDrive
        url: "/task-scanning-onedrive.html"
      - title: Analyser les comptes SharePoint
        url: "/task-scanning-sharepoint.html"
      - title: Analyser les comptes Google Drive
        url: "/task-scanning-google-drive.html"
      - title: Analysez le stockage objet à l'aide du protocole S3
        url: "/task-scanning-object-storage.html"
    - title: Gérer les opérations de données
      entries:
      - title: Affichez les détails de gouvernance relatifs aux données dans le tableau
          de bord gouvernance
        url: "/task-controlling-governance-dashboard-deprecated.html"
      - title: Organisez vos données privées
        url: "/task-org-private-data.html"
      - title: Gérez vos données privées
        url: "/task-managing-highlights.html"
      - title: Ajoutez des identifiants de données personnels personnalisés
        url: "/task-managing-data-fusion.html"
      - title: Afficher l'état des actions de classification BlueXP
        url: "/task-view-compliance-actions.html"
      - title: Vérifiez l'historique des actions de classification BlueXP
        url: "/task-audit-data-sense-actions.html"
      - title: Réduisez la vitesse d'analyse de la classification BlueXP
        url: "/task-reduce-scan-speed.html"
      - title: Supprimez un compte OneDrive, SharePoint ou Google Drive
        url: "/task-managing-compliance-deprecated.html"
  - title: Référence
    entries:
    - title: Types d'instances de classification BlueXP pris en charge
      url: "/reference-instance-types.html"
    - title: Métadonnées collectées à partir des sources de données
      url: "/reference-collected-metadata.html"
    - title: Connectez-vous au système de classification BlueXP
      url: "/reference-log-in-to-instance.html"
    - title: API de classification BlueXP
      url: "/api-classification.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: FAQ
    url: "/faq-cloud-compliance.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
