---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, data sense, classification, bluexp, scan shares 
summary: 'Les limitations connues identifient les fonctions qui ne sont pas prises en charge par cette version du produit ou qui n"interagissent pas correctement avec elle. Examinez attentivement ces limites.' 
---
= Limitations connues dans la classification BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les fonctions qui ne sont pas prises en charge ou qui n’interagissent pas correctement dans cette version. Examinez attentivement ces limites.



== Options de classification BlueXP désactivées

La version de décembre 2023 (version 1.26.6) a supprimé les options suivantes :

* L'option permettant d'activer la collecte des journaux d'audit a été désactivée.
* Lors de l'enquête sur les annuaires, l'option permettant de calculer le nombre de données d'informations personnelles identifiables (PII) par annuaires n'est pas disponible.
* L'option d'intégration des données à l'aide d'étiquettes Azure information protection (AIP) a été désactivée.




== Analyse de classification BlueXP

Les limitations suivantes se produisent avec les analyses de classification BlueXP.



=== La classification BlueXP analyse un seul partage sous un volume

Si vous avez plusieurs partages de fichiers sous un seul volume, la classification BlueXP analyse le partage avec la hiérarchie la plus élevée. Par exemple, si vous avez des partages comme les suivants :

* /A
* /A/B.
* /C
* /D/E.


Dans cette configuration, seules les données de /A sont analysées. Les données de /C et /D ne le sont pas.

.Solution de contournement
Il existe une solution pour vous assurer que vous analysez les données de tous les partages de votre volume. Voici la procédure à suivre :

. Dans l'environnement de travail, ajoutez le volume à scanner.
. Une fois que la classification BlueXP a terminé l'analyse du volume, accédez à la page _Data Investigation_ et créez un filtre pour voir quel partage est en cours d'analyse :
+
Filtrez les données par « Nom de l'environnement de travail » et « Type de répertoire = Partage » pour voir quel partage est analysé.

. Obtenez la liste complète des partages qui existent dans le volume pour voir quels partages ne sont pas analysés.
. link:task-scanning-file-shares.html["Ajoutez les partages restants à un groupe de partages"].
+
Ajoutez toutes les actions individuellement, par exemple :

+
....
/C
/D
....
. Procédez comme suit pour chaque volume de l'environnement de travail qui a plusieurs partages.




=== Horodatage du dernier accès

Lorsque la classification BlueXP analyse un répertoire, l'analyse affecte le champ **Dernier accès** du répertoire. Lorsque vous consultez ce champ, les métadonnées reflètent soit la date et l'heure de l'analyse, soit la date du dernier accès au répertoire.
