---
sidebar: sidebar 
permalink: reference-private-data-categories.html 
keywords: personal files, personal data, sensitive personal files, sensitive personal data, categories, health data, ethnic origin, political opinions, gdpr, email address, credit card, ip address, iban, national ID, identifier, sex, criminal, compliance, privacy, 
summary: Il existe de nombreux types de données privées que la classification BlueXP peut identifier dans vos volumes, dans des compartiments Amazon S3, dans des bases de données, des dossiers OneDrive, des comptes SharePoint, Et Google Drive. 
---
= Catégories de données privées classées par BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe de nombreux types de données privées que la classification BlueXP peut identifier dans vos volumes et vos bases de données.

La classification BlueXP identifie deux types de données personnelles :

* *Informations personnelles identifiables (PII)*
* *Informations personnelles sensibles (SPII)*



TIP: Si vous avez besoin de la classification BlueXP  pour identifier d'autres types de données privées, comme des numéros d'identification nationaux supplémentaires ou des identifiants de soins de santé, contactez votre gestionnaire de compte.



== Types de données personnelles

Les données personnelles, ou _informations personnelles identifiables_ (PII), qui se trouvent dans les fichiers peuvent être des données personnelles générales ou des identificateurs nationaux. La troisième colonne du tableau ci-dessous indique si la classification BlueXP utilise link:task-controlling-private-data.html#view-files-that-contain-personal-data["validation de proximité"^] pour valider ses résultats pour l'identificateur.

Les langues dans lesquelles ces éléments peuvent être reconnus sont identifiées dans le tableau.

[cols="13,37,10,8,8,8,8,8"]
|===
| Type | Identificateur | Validation de proximité ? | Anglais | Allemand | Espagnol | Français | Japonais 


.6+| Généralités | Numéro de carte de crédit | Non | ✓ | ✓ | ✓ |  | ✓ 


| Sujets de données | Non | ✓ | ✓ | ✓ |  |  


| Adresse électronique | Non | ✓ | ✓ | ✓ |  | ✓ 


| Numéro IBAN (numéro de compte bancaire international) | Non | ✓ | ✓ | ✓ |  | ✓ 


| Adresse IP | Non | ✓ | ✓ | ✓ |  | ✓ 


| Mot de passe | Oui. | ✓ | ✓ | ✓ |  | ✓ 


.57+| Identifiants nationaux | TFN australien (Numéro de dossier fiscal) | Oui. | ✓ | ✓ | ✓ |  |  


| Permis de conduire australien | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro d'assurance-maladie australien | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro de passeport australien | Oui. | ✓ | ✓ | ✓ |  |  


| SSN autrichien | Oui. | ✓ | ✓ | ✓ |  |  


| Carte d'identité belge (Numero National) | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro de carte d'identité Botswana (Omang) | Oui. | ✓ | ✓ | ✓ |  |  


| Botswana Numéro de passeport | Oui. | ✓ | ✓ | ✓ |  |  


| ID brésilien (CPF) | Oui. | ✓ | ✓ | ✓ |  |  


| Passeport britannique | Oui. | ✓ | ✓ | ✓ |  |  


| ID bulgare (UCN) | Oui. | ✓ | ✓ | ✓ |  |  


| ID croate (OIB) | Oui. | ✓ | ✓ | ✓ |  |  


| Chypre Numéro d'identification fiscale (TIC) | Oui. | ✓ | ✓ | ✓ |  |  


| Tchèque/slovaque ID | Oui. | ✓ | ✓ | ✓ |  |  


| ID danois (RCP) | Oui. | ✓ | ✓ | ✓ |  |  


| ID néerlandais (BSN) | Oui. | ✓ | ✓ | ✓ |  |  


| ID estonien | Oui. | ✓ | ✓ | ✓ |  |  


| ID finlandais (HETU) | Oui. | ✓ | ✓ | ✓ |  |  


| Permis de conduire français | Oui. | ✓ | ✓ | ✓ | ✓ |  


| ID en français | Oui. | ✓ | ✓ | ✓ | ✓ |  


| INSEE français | Oui. | ✓ | ✓ | ✓ | ✓ |  


| Numéro de sécurité sociale en français | Oui. | ✓ | ✓ | ✓ | ✓ |  


| Numéro d'identification fiscale (SPI) | Oui. | ✓ | ✓ | ✓ | ✓ |  


| ID allemand (Personalausweisnummer) | Oui. | ✓ | ✓ | ✓ |  |  


| ID interne allemand pour les transferts bancaires | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro de sécurité sociale allemand (Sozialversicherungsnummer) | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro d'identification fiscale allemand (identifiant Steierliche) | Oui. | ✓ | ✓ | ✓ |  |  


| Pièce d'identité grecque | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro d'identification fiscale hongrois | Oui. | ✓ | ✓ | ✓ |  |  


| Irish ID (PPS) | Oui. | ✓ | ✓ | ✓ |  |  


| ID israélien | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro d'identification fiscal italien | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro d'identification personnel japonais (personnel et entreprise) | Oui. | ✓ | ✓ | ✓ |  | ✓ 


| Carte d'identité lettone | Oui. | ✓ | ✓ | ✓ |  |  


| Carte d'identité lituanienne | Oui. | ✓ | ✓ | ✓ |  |  


| Luxembourg ID | Oui. | ✓ | ✓ | ✓ |  |  


| Identifiant maltais | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro du Service national de santé (NHS) | Oui. | ✓ | ✓ | ✓ |  |  


| Compte bancaire de la Nouvelle-Zélande | Oui. | ✓ | ✓ | ✓ |  |  


| Permis de conduire de la Nouvelle-Zélande | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro IRD de Nouvelle-Zélande (ID taxe) | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro NHI (National Health Index) de la Nouvelle-Zélande | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro de passeport de la Nouvelle-Zélande | Oui. | ✓ | ✓ | ✓ |  |  


| ID polonais (PESEL) | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro d'identification fiscale portugais (FNI) | Oui. | ✓ | ✓ | ✓ |  |  


| ID roumain (CNP) | Oui. | ✓ | ✓ | ✓ |  |  


| Carte d'identité nationale d'enregistrement de Singapour (NRIC) | Oui. | ✓ | ✓ | ✓ |  |  


| ID slovène (EMSO) | Oui. | ✓ | ✓ | ✓ |  |  


| Carte d'identité sud-africaine | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro d'identification fiscale espagnol | Oui. | ✓ | ✓ | ✓ |  |  


| Carte d'identité suédoise | Oui. | ✓ | ✓ | ✓ |  |  


| Permis de conduire Texas | Oui. | ✓ | ✓ | ✓ |  |  


| ROYAUME-UNI ID (NINO) | Oui. | ✓ | ✓ | ✓ |  |  


| Permis de conduire de Californie aux États-Unis | Oui. | ✓ | ✓ | ✓ |  |  


| Permis de conduire de l'Indiana des États-Unis | Oui. | ✓ | ✓ | ✓ |  |  


| Permis de conduire New York aux États-Unis | Oui. | ✓ | ✓ | ✓ |  |  


| Numéro de sécurité sociale des États-Unis (SSN) | Oui. | ✓ | ✓ | ✓ |  |  
|===


== Types de données personnelles sensibles

La classification BlueXP peut trouver les informations personnelles sensibles suivantes (SPII) dans des fichiers.

Les éléments de cette catégorie ne peuvent être reconnus qu'en anglais pour le moment.

* *Référence pour les procédures pénales* : données concernant les condamnations et les infractions criminelles d'une personne physique.
* *Référence ethnique* : données concernant l'origine raciale ou ethnique d'une personne physique.
* * Référence en matière de santé* : données concernant la santé d'une personne physique.
* *Codes médicaux CIM-9-cm* : codes utilisés dans l'industrie médicale et de la santé.
* *Codes médicaux CIM-10-cm* : codes utilisés dans l'industrie médicale et de la santé.
* *Croyances philosophiques référence*: Données concernant les croyances philosophiques d'une personne physique.
* *Opinions politiques référence*: Données concernant les opinions politiques d'une personne physique.
* *Croyances religieuses référence* : données concernant les croyances religieuses d'une personne physique.
* *Sexe vie ou orientation référence* : données concernant la vie sexuelle ou l'orientation sexuelle d'une personne physique.




== Types de catégories

La classification BlueXP classe vos données comme suit.

La plupart de ces catégories peuvent être reconnues en anglais, allemand et espagnol.

[cols="25,25,15,15,15"]
|===
| Catégorie | Type | Anglais | Allemand | Espagnol 


.4+| Finances | Bilans | ✓ | ✓ | ✓ 


| Bons de commande | ✓ | ✓ | ✓ 


| Factures | ✓ | ✓ | ✓ 


| Rapports trimestriels | ✓ | ✓ | ✓ 


.6+| RH | Vérifications des antécédents | ✓ |  | ✓ 


| Plans de rémunération | ✓ | ✓ | ✓ 


| Contrats employés | ✓ |  | ✓ 


| Évaluations des employés | ✓ |  | ✓ 


| Santé | ✓ |  | ✓ 


| Reprend | ✓ | ✓ | ✓ 


.2+| Légal | NDAS | ✓ | ✓ | ✓ 


| Contrats fournisseur-client | ✓ | ✓ | ✓ 


.2+| Marketing | Campagnes | ✓ | ✓ | ✓ 


| Conférences | ✓ | ✓ | ✓ 


| Exploitation | Rapports d'audit | ✓ | ✓ | ✓ 


| Ventes | Commandes | ✓ | ✓ |  


.4+| Administratifs | RFI | ✓ |  | ✓ 


| RFP | ✓ |  | ✓ 


| CAHIER DES CHARGES | ✓ | ✓ | ✓ 


| Formation | ✓ | ✓ | ✓ 


| Assistance | Plaintes et tickets | ✓ | ✓ | ✓ 
|===
Les métadonnées suivantes sont également classées en catégories et identifiées dans les mêmes langues prises en charge :

* Données applicatives
* Archiver les fichiers
* Audio
* Fils d'Ariane dans la classification BlueXP
Données d'applications d'entreprise
* Fichiers CAO
* Code
* Corrompu
* Base de données et fichiers d'index
* Fichiers de conception
* Données d'application de messagerie
* Crypté (fichiers avec un score d'entropie élevé)
* Exécutables
* Données d'applications financières
* Données d'application de santé
* Images
* Journaux
* Documents divers
* Présentations diverses
* Feuilles de calcul diverses
* Divers « Inconnu »
* Fichiers protégés par mot de passe
* Données structurées
* Vidéos
* Fichiers de zéro octet




== Types de fichiers

La classification BlueXP analyse tous les fichiers pour rechercher des informations par catégorie et par métadonnées, et affiche tous les types de fichiers dans la section types de fichiers du tableau de bord.

Toutefois, lorsque la classification BlueXP détecte des informations à caractère personnel (PII) ou lorsqu'elle effectue une recherche DSAR, seuls les formats de fichier suivants sont pris en charge :

`+.CSV, .DCM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



== Exactitude des informations trouvées

NetApp ne peut pas garantir l'exactitude à 100 % des données personnelles et des données personnelles sensibles identifiées par la classification BlueXP. Vous devez toujours valider les informations en examinant les données.

D'après nos tests, le tableau ci-dessous précise les informations trouvées par la classification BlueXP. Nous la décomposent par _Precision_ et _rappel_:

Précision:: La probabilité que la classification BlueXP trouve ait été correctement identifiée. Par exemple, un taux de précision de 90 % pour les données personnelles signifie que 9 fichiers sur 10 identifiés comme contenant des renseignements personnels, contiennent en fait des renseignements personnels. 1 fichier sur 10 serait un faux positif.
Rappel:: Probabilité que la classification BlueXP trouve ce qu'elle doit. Par exemple, un taux de rappel de 70 % pour les données personnelles signifie que la classification BlueXP peut identifier 7 fichiers sur 10 qui contiennent réellement des données personnelles dans votre entreprise. 30 % des données sont classifiées et n'apparaîtront pas dans le tableau de bord.


Nous améliorons constamment la précision de nos résultats. Ces améliorations seront automatiquement disponibles dans les futures versions de classification BlueXP.

[cols="25,20,20"]
|===
| Type | Précision | Rappel 


| Données personnelles - général | 90 à 95 % | 60 à 80 % 


| Données personnelles - identificateurs de pays | 30 à 60 % | 40 à 60 % 


| Données personnelles sensibles | 80 à 95 % | 20 à 30 % 


| Catégories | 90 à 97 % | 60 à 80 % 
|===