---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: BlueXP classification, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: 'Le logiciel de classification BlueXP doit s"exécuter sur un hôte répondant à des exigences spécifiques en termes de système d"exploitation, de RAM, de logiciels, etc. Lors du déploiement de la classification BlueXP dans le cloud, nous vous recommandons d"utiliser un système présentant les caractéristiques « grandes » pour bénéficier de fonctionnalités complètes.' 
---
= Types d'instances de classification BlueXP pris en charge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le logiciel de classification BlueXP doit s'exécuter sur un hôte répondant à des exigences spécifiques en termes de système d'exploitation, de RAM, de logiciels, etc. Lors du déploiement de la classification BlueXP dans le cloud, nous vous recommandons d'utiliser un système présentant les caractéristiques « grandes » pour bénéficier de fonctionnalités complètes.

Vous pouvez déployer la classification BlueXP sur un système avec moins de processeurs et moins de RAM, mais l'utilisation de systèmes moins puissants comporte certaines limitations. link:concept-cloud-compliance.html#using-a-smaller-instance-type["Découvrez ces limites"^].

Dans les tableaux suivants, si le système marqué comme « par défaut » n'est pas disponible dans la région dans laquelle vous installez la classification BlueXP, le système suivant du tableau sera déployé.



== Types d'instances AWS

[cols="20,30,25"]
|===
| Taille du système | Caractéristiques | Type d'instance 


| Très grand | 32 processeurs, 128 Go de RAM, 1 Tio de SSD gp3 | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.8xlarge"^] (valeur par défaut) 


| Grand | 16 processeurs, 64 Go de RAM, SSD de 500 Gio | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.4xlarge"^] (par défaut) m6a.4xlarge m5a.4xlarge m5.4xlarge m4.4xlarge 


| Moyen | 8 processeurs, 32 Go de RAM, SSD de 200 Gio | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.2xlarge"^] (par défaut) m6a.2xlarge m5a.2xlarge m5.2xlarge m4.2xlarge 


| Petit | 8 processeurs, 16 Go de RAM, SSD de 100 Gio | https://aws.amazon.com/ec2/instance-types/c6a/["c6a.2xlarge"^] (par défaut) c5a.2xlarge c5.2xlarge c4.2xlarge 
|===


== Types d'instances Azure

[cols="20,30,25"]
|===
| Taille du système | Caractéristiques | Type d'instance 


| Très grand | 32 processeurs, 128 Go de RAM, disque OS (2,048 Gio, débit min. De 250 Mo/s) et disque de données (SSD de 1 Tio, débit min. De 750 Mo/s) | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dv3-series["Standard_D32_v3"^] (valeur par défaut) 


| Grand | 16 processeurs, 64 Go de RAM, SSD de 500 Gio | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dsv3-series["Standard_D16s_v3"^] (valeur par défaut) 
|===


== Types d'instances GCP

[cols="20,30,25"]
|===
| Taille du système | Caractéristiques | Type d'instance 


| Grand | 16 processeurs, 64 Go de RAM, SSD de 500 Gio | https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines["n2-standard-16"^] (par défaut) n2d-standard-16 n1-standard-16 
|===