---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: data sense, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: 'Le logiciel de détection des données doit être exécuté sur un hôte qui répond à des exigences spécifiques du système d"exploitation, de la RAM, des exigences logicielles, etc. Lors du déploiement de Data Sense dans le cloud, nous vous recommandons d"utiliser un système présentant les caractéristiques « grandes » pour bénéficier de fonctionnalités complètes.' 
---
= Types d'instances Data Sense pris en charge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le logiciel de détection des données doit être exécuté sur un hôte qui répond à des exigences spécifiques du système d'exploitation, de la RAM, des exigences logicielles, etc. Lors du déploiement de Data Sense dans le cloud, nous vous recommandons d'utiliser un système présentant les caractéristiques « grandes » pour bénéficier de fonctionnalités complètes.

Vous pouvez déployer Data Sense sur un système avec moins de processeurs et moins de RAM, mais il ya certaines limites quand l'utilisation de ces systèmes moins puissants. link:concept-cloud-compliance.html#using-a-smaller-instance-type["Découvrez ces limites"^].

Dans les tableaux suivants, si le système marqué par défaut n'est pas disponible dans la région où vous installez Data Sense, le système suivant de la table sera déployé.



== Types d'instances AWS

[cols="20,30,25"]
|===
| Taille du système | Caractéristiques | Type d'instance 


| Grand | 16 processeurs, 64 Go de RAM, SSD de 500 Gio | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.4xlarge"^] (par défaut) m6a.4xlarge m5a.4xlarge m5.4xlarge m4.4xlarge 


| Moyen | 8 processeurs, 32 Go de RAM, SSD de 200 Gio | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.2xlarge"^] (par défaut) m6a.2xlarge m5a.2xlarge m5.2xlarge m4.2xlarge 


| Petit | 8 processeurs, 16 Go de RAM, SSD de 100 Gio | https://aws.amazon.com/ec2/instance-types/c6a/["c6a.2xlarge"^] (par défaut) c5a.2xlarge c5.2xlarge c4.2xlarge 
|===


== Types d'instances Azure

[cols="20,30,25"]
|===
| Taille du système | Caractéristiques | Type d'instance 


| Grand | 16 processeurs, 64 Go de RAM, SSD de 500 Gio | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dsv3-series["Standard_D16s_v3"^] (valeur par défaut) 
|===


== Types d'instances GCP

[cols="20,30,25"]
|===
| Taille du système | Caractéristiques | Type d'instance 


| Grand | 16 processeurs, 64 Go de RAM, SSD de 500 Gio | https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines["n2-standard-16"^] (par défaut) n2d-standard-16 n1-standard-16 
|===