---
sidebar: sidebar 
permalink: task-audit-data-sense-actions.html 
keywords: compliance, actions, view progress, audit, logs, installation 
summary: 'Les activités de gestion des journaux de classification BlueXP qui ont été effectuées sur des fichiers depuis tous les environnements de travail et toutes les sources de données que la classification BlueXP analyse. La classification BlueXP consigne également les activités liées au déploiement de l"instance de classification BlueXP.' 
---
= Vérifiez l'historique des actions de classification BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les activités de gestion des journaux de classification BlueXP qui ont été effectuées sur des fichiers depuis tous les environnements de travail et toutes les sources de données que la classification BlueXP analyse. La classification BlueXP consigne également les activités liées au déploiement de l'instance de classification BlueXP.

Vous pouvez afficher le contenu des fichiers journaux d'audit de classification BlueXP ou les télécharger pour voir quelles modifications de fichier ont été apportées et à quelle date. Par exemple, vous pouvez voir quelle demande a été émise, l'heure de la demande et des détails tels que l'emplacement source en cas de suppression d'un fichier ou l'emplacement source et de destination en cas de déplacement d'un fichier.

[]
====
*REMARQUE* ces informations ne concernent que les versions 1.30 et antérieures de l'héritage de classification BlueXP.

====


== Contenu du fichier journal

Chaque ligne du journal d'audit contient des informations dans ce format :

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* Date et heure : horodatage complet de l'événement
* État - INFO, AVERTISSEMENT
* Type d'action (supprimer, copier, déplacer, créer la stratégie, mettre à jour la stratégie, Analyse des fichiers, téléchargement du rapport JSON, etc.)
* Nom du fichier (si l'action est pertinente pour un fichier)
* Détails de l'action - ce qui a été fait : dépend de l'action
+
** Nom de la règle
** Pour déplacer - Source et destination
** Pour la copie - Source et destination
** Pour balise - nom de balise
** Pour attribuer à - nom d'utilisateur
** Pour une alerte par e-mail : adresse e-mail/compte




Par exemple, les lignes suivantes du fichier journal indiquent une opération de copie réussie et une opération de copie ayant échoué.

....
2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE
....


== Emplacements des fichiers journaux

Les fichiers journaux d'audit de gestion se trouvent sur la machine de classification BlueXP dans : `/opt/netapp/audit_logs/`

Les fichiers journaux d'audit d'installation sont écrits dans `/opt/netapp/install_logs/`

Chaque fichier journal peut avoir une taille maximale de 10 Mo. Lorsque cette limite est atteinte, un nouveau fichier journal démarre. Les fichiers journaux sont nommés « DataSense_audit.log », « DataSense_audit.log.1 », « DataSense_audit.log.2 », etc. Un maximum de 100 fichiers journaux sont conservés sur le système - les anciens fichiers journaux sont automatiquement supprimés une fois le maximum atteint.



== Accédez aux fichiers journaux

Vous devez vous connecter au système de classification BlueXP pour accéder aux fichiers journaux. Découvrez comment link:reference-log-in-to-instance.html["Connectez-vous au système de classification BlueXP"] Selon que vous avez installé le logiciel manuellement sur une machine Linux ou si vous avez déployé l'instance dans le cloud.
