---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, bluexp, data sense, get started, deploy, bluexp classification, cloud compliance access, compliance, on-premises, linux, test linux system, docker, podman, ubuntu, rhel, dark site, bluexp 
summary: 'Avant d"installer manuellement la classification BlueXP sur un hôte Linux, vous pouvez exécuter un script sur l"hôte pour vérifier que toutes les conditions préalables requises pour l"installation de la classification BlueXP sont en place. Vous pouvez exécuter ce script sur un hôte Linux de votre réseau ou sur un hôte Linux du cloud. L"hôte peut être connecté à Internet, ou l"hôte peut résider sur un site qui n"a pas accès à Internet.' 
---
= Vérifiez que votre hôte Linux est prêt à installer la classification BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant d'installer manuellement la classification BlueXP sur un hôte Linux, vous pouvez exécuter un script sur l'hôte pour vérifier que toutes les conditions préalables requises pour l'installation de la classification BlueXP sont en place. Vous pouvez exécuter ce script sur un hôte Linux de votre réseau ou sur un hôte Linux du cloud. L'hôte peut être connecté à Internet, ou l'hôte peut résider sur un site qui n'a pas accès à Internet (un _site sombre_).

Il existe également un script de test prérequis qui fait partie du script d'installation de la classification BlueXP. Le script décrit ici est spécialement conçu pour les utilisateurs qui souhaitent vérifier l'hôte Linux indépendamment de l'exécution du script d'installation de classification BlueXP.



== Mise en route

Vous effectuerez les tâches suivantes.

. Si vous ne l'avez pas déjà installé, installez un connecteur BlueXP. Vous pouvez exécuter le script de test sans avoir installé de connecteur, mais le script vérifie la connectivité entre le connecteur et la machine hôte de classification BlueXP. Il est donc recommandé de disposer d'un connecteur.
. Préparer le porteur et vérifier qu'il répond à toutes les exigences.
. Activez l'accès Internet sortant à partir de la machine hôte de classification BlueXP.
. Vérifiez que tous les ports requis sont activés sur tous les systèmes.
. Téléchargez et exécutez le script de test requis.




== Créer un connecteur

Un connecteur BlueXP est requis avant de pouvoir installer et utiliser la classification BlueXP. Vous pouvez cependant exécuter le script Prerequisites sans connecteur.

C'est possible https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html["Installer le connecteur sur site"^] Sur un hôte Linux de votre réseau ou sur un hôte Linux du cloud. Certains utilisateurs qui prévoient d'installer la classification BlueXP sur site peuvent également choisir d'installer le connecteur sur site.

Pour créer un connecteur dans l'environnement de votre fournisseur de cloud, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["Création d'un connecteur dans AWS"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Création d'un connecteur dans Azure"^], ou https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Création d'un connecteur dans GCP"^].

Vous aurez besoin de l'adresse IP ou du nom d'hôte du système de connecteur lors de l'exécution du script Prerequisites. Vous aurez ces informations si vous avez installé le connecteur sur votre site. Si le connecteur est déployé dans le cloud, vous pouvez trouver ces informations à partir de la console BlueXP : cliquez sur l'icône aide, sélectionnez *support* et cliquez sur *BlueXP Connector*.



== Vérifiez les besoins de l'hôte

Le logiciel de classification BlueXP doit s'exécuter sur un hôte répondant à des exigences spécifiques en termes de système d'exploitation, de RAM, de logiciels, etc.

* La classification BlueXP n'est pas prise en charge sur un hôte partagé avec d'autres applications : l'hôte doit être un hôte dédié.
* Lors de la création du système hôte sur site, vous pouvez choisir parmi ces tailles de système, en fonction de la taille du dataset sur lequel vous prévoyez d'effectuer l'analyse de classification BlueXP.
+
[cols="17,17,27,31"]
|===
| Taille du système | CPU | RAM (la mémoire d'échange doit être désactivée) | Disque 


| *Très grand* | 32 processeurs | 128 GO DE RAM | 1 To SSD sur /, ou
- 100 Gio disponible sur /opt
- 895 Gio disponible sur /var/lib/docker
- 5 Gio sur /tmp 


| *Grand* | 16 processeurs | 64 GO DE RAM | 500 Gio de SSD sur /, ou
- 100 Gio disponible sur /opt
- 395 Gio disponible sur /var/lib/docker ou pour Podman /var/lib/containers ou pour Podman /var/lib/containers
- 5 Gio sur /tmp 
|===
* Lors du déploiement d'une instance de calcul dans le cloud pour votre installation de classification BlueXP, nous vous recommandons de opter pour un système qui répond à la configuration requise pour les « grands » systèmes ci-dessus :
+
** *Type d'instance Amazon Elastic Compute Cloud (Amazon EC2)*: Nous recommandons "m6i.4xlarge". link:reference-instance-types.html#aws-instance-types["Consultez la section autres types d'instances AWS"^].
** *Taille de VM Azure*: Nous recommandons "Standard_D16s_v3". link:reference-instance-types.html#azure-instance-types["Consultez la section autres types d'instances Azure"^].
** *Type de machine GCP*: Nous recommandons "n2-standard-16". link:reference-instance-types.html#gcp-instance-types["Voir autres types d'instances GCP"^].


* *Autorisations de dossier UNIX* : les autorisations UNIX minimales suivantes sont requises :
+
[cols="25,25"]
|===
| Dossier | Autorisations minimales 


| /tmp | `rwxrwxrwt` 


| /opt | `rwxr-xr-x` 


| /var/lib/docker | `rwx------` 


| /usr/lib/systemd/system | `rwxr-xr-x` 
|===
* *Système d'exploitation* :
+
** Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de mise en conteneurs Docker :
+
*** Red Hat Enterprise Linux version 7.8 et 7.9
*** Ubuntu 22.04 (requiert la classification BlueXP version 1.23 ou supérieure)
*** Ubuntu 24.04 (nécessite la classification BlueXP  version 1.23 ou supérieure)


** Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP version 1.30 ou supérieure :
+
*** Red Hat Enterprise Linux version 8.8, 9.0, 9.1, 9.2, 9.3, 9.4




* *Gestion des abonnements Red Hat* : l'hôte doit être enregistré auprès de la gestion des abonnements Red Hat. S'il n'est pas enregistré, le système ne peut pas accéder aux référentiels pour mettre à jour les logiciels tiers requis pendant l'installation.
* *Logiciels supplémentaires* : vous devez installer les logiciels suivants sur l'hôte avant d'installer la classification BlueXP :
+
** En fonction du système d'exploitation que vous utilisez, vous devrez installer l'un des moteurs de mise en conteneurs :
+
*** Docker Engine version 19.3.1 ou supérieure. https://docs.docker.com/engine/install/["Voir les instructions d'installation"^].
*** Podman version 4 ou supérieure. Pour installer Podman, entrez (`sudo yum install podman netavark -y`).






* Python version 3.6 ou supérieure. https://www.python.org/downloads/["Voir les instructions d'installation"^].
+
** *Considérations NTP* : NetApp recommande de configurer le système de classification BlueXP pour utiliser un service NTP (Network Time Protocol). L'heure doit être synchronisée entre le système de classification BlueXP et le système BlueXP Connector.
** *Firesund considérations*: Si vous prévoyez d'utiliser `firewalld`, Nous vous recommandons de l'activer avant d'installer la classification BlueXP. Exécutez les commandes suivantes pour configurer `firewalld` Pour qu'il soit compatible avec la classification BlueXP :
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
Si vous prévoyez d'utiliser des hôtes de classification BlueXP supplémentaires comme nœuds d'analyse (dans un modèle distribué), ajoutez ces règles à votre système principal à ce stade :

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
Notez que vous devez redémarrer Docker ou Podman chaque fois que vous activez ou mettez à jour `firewalld` paramètres.







== Assurez un accès Internet sortant à partir de la classification BlueXP

La classification BlueXP nécessite un accès Internet sortant. Si votre réseau physique ou virtuel utilise un serveur proxy pour l'accès à Internet, assurez-vous que l'instance de classification BlueXP dispose d'un accès Internet sortant pour contacter les terminaux suivants.


TIP: Cette section n'est pas requise pour les systèmes hôtes installés sur des sites sans connexion Internet.

[cols="43,57"]
|===
| Terminaux | Objectif 


| \https://api.bluexp.netapp.com | Communication avec le service BlueXP, qui inclut les comptes NetApp. 


| \https://netapp-cloud-account.auth0.com \https://auth0.com | Communication avec le site Web BlueXP pour l'authentification centralisée des utilisateurs. 


| \https://support.compliance.api.bluexp.netapp.com/ \https://hub.docker.com \https://auth.docker.io \https://registry-1.docker.io \https://index.docker.io/ \https://dseasb33srnrn.cloudfront.net/ \https://production.cloudflare.docker.com/ | Permet d'accéder aux images logicielles, aux manifestes, aux modèles et à l'envoi de journaux et de mesures. 


| \https://support.compliance.api.bluexp.netapp.com/ | Permet à NetApp de diffuser des données à partir d'enregistrements d'audit. 


| \https://github.com/docker \https://download.docker.com | Fournit les packages prérequis pour l'installation de docker. 


| \http://packages.ubuntu.com/
\http://archive.ubuntu.com | Fournit les packages prérequis pour l'installation d'Ubuntu. 
|===


== Vérifiez que tous les ports requis sont activés

Vous devez vous assurer que tous les ports requis sont ouverts pour la communication entre le connecteur, la classification BlueXP, Active Directory et vos sources de données.

[cols="25,25,50"]
|===
| Type de connexion | Ports | Description 


| Classification de Connector <> BlueXP | 8080 (TCP), 443 (TCP) et 80. 9000 | Les règles de pare-feu ou de routage du connecteur doivent autoriser le trafic entrant et sortant via le port 443 vers et depuis l'instance de classification BlueXP. Assurez-vous que le port 8080 est ouvert pour voir la progression de l'installation dans BlueXP. Si un pare-feu est utilisé sur l'hôte Linux, le port 9000 est requis pour les processus internes d'un serveur Ubuntu. 


| Connecteur <> cluster ONTAP (NAS) | 443 (TCP)  a| 
BlueXP détecte les clusters ONTAP via HTTPS. Si vous utilisez des stratégies de pare-feu personnalisées, l'hôte du connecteur doit autoriser l'accès HTTPS sortant via le port 443. Si le connecteur est dans le cloud, toutes les communications sortantes sont autorisées par le pare-feu ou les règles de routage prédéfinies.

|===


== Exécutez le script BlueXP classification Prerequisites

Procédez comme suit pour exécuter le script BlueXP classification Prerequisites.

https://youtu.be/_RCYpuLXiV0?si=QLGUw8mqPrz9qs4B["Regardez cette vidéo"^] Pour savoir comment exécuter le script Prerequisites et interpréter les résultats.

.Ce dont vous avez besoin
* Vérifiez que votre système Linux est conforme à la <<Vérifiez les besoins de l'hôte,configuration requise pour l'hôte>>.
* Vérifiez que le système dispose des deux packages logiciels prérequis installés (Docker Engine ou Podman et Python 3).
* Assurez-vous que vous disposez des privilèges root sur le système Linux.


.Étapes
. Téléchargez le script BlueXP classification Prerequisites depuis le https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["Site de support NetApp"^]. Le fichier que vous devez sélectionner est nommé *standalone-pre-tester-<version>*.
. Copiez le fichier sur l'hôte Linux que vous souhaitez utiliser (à l'aide de `scp` ou une autre méthode).
. Attribuez des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.25.0
----
. Exécutez le script à l'aide de la commande suivante.
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
----
+
Ajoutez l'option "--darksite" uniquement si vous exécutez le script sur un hôte qui n'a pas accès à Internet. Certains tests préalables sont ignorés lorsque l'hôte n'est pas connecté à Internet.

. Le script vous demande l'adresse IP de la machine hôte de classification BlueXP.
+
** Entrez l'adresse IP ou le nom d'hôte.


. Le script vous demande si BlueXP Connector est installé.
+
** Entrez *N* si vous n'avez pas de connecteur installé.
** Entrez *y* si vous avez un connecteur installé. Puis entrez l'adresse IP ou le nom d'hôte du connecteur BlueXP afin que le script de test puisse tester cette connectivité.


. Le script exécute une variété de tests sur le système et affiche les résultats au fur et à mesure qu'il progresse. Une fois terminé, il écrit un journal de la session dans un fichier nommé `prerequisites-test-<timestamp>.log` dans le répertoire `/opt/netapp/install_logs`.


.Résultat
Si tous les tests prérequis ont été correctement exécutés, vous pouvez installer la classification BlueXP sur l'hôte lorsque vous êtes prêt.

Si des problèmes ont été découverts, ils sont classés comme « recommandés » ou « obligatoires » pour être résolus. Les problèmes recommandés sont généralement des éléments qui ralentiraient l'analyse de classification BlueXP et les tâches de catégorisation. Ces éléments n'ont pas besoin d'être corrigés, mais vous pouvez les corriger.

Si vous rencontrez des problèmes « obligatoires », vous devez résoudre les problèmes et exécuter à nouveau le script de test prérequis.
