---
sidebar: sidebar 
permalink: task-add-group-id-as-open.html 
keywords: permissions, open to organization, file access 
summary: 'Lorsque les ID de groupe sont attachés à des fichiers ou dossiers dans des partages de fichiers NFS, ils définissent les autorisations pour le fichier ou le dossier, par exemple s"ils sont « ouverts à l"organisation ». Si certains ID de groupe (GID) ne sont pas initialement configurés avec le niveau d"autorisation « Ouvrir à l"organisation », vous pouvez ajouter cette autorisation au GID pour que tous les fichiers et dossiers auxquels ce GID est rattaché soient considérés comme « ouverts à l"organisation ».' 
---
= Définir des ID de groupe supplémentaires comme « ouverts à l'organisation »
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque des ID de groupe (GID) sont attachés à des fichiers ou dossiers dans des partages de fichiers NFS, ils définissent les autorisations pour le fichier ou le dossier, par exemple s'ils sont « ouverts à l'organisation ». Si certains ID de groupe (GID) ne sont pas initialement configurés avec le niveau d'autorisation « Ouvrir à l'organisation », vous pouvez ajouter cette autorisation au GID pour que tous les fichiers et dossiers auxquels ce GID est rattaché soient considérés comme « ouverts à l'organisation ».

Après avoir effectué cette modification et que la classification BlueXP analyse à nouveau vos fichiers et dossiers, tous les fichiers et dossiers auxquels ces ID de groupe sont associés affichent cette autorisation dans la page Détails de l'investigation et ils apparaissent également dans les rapports où vous affichez les autorisations de fichier.

Pour activer cette fonctionnalité, vous devez vous connecter au système de classification BlueXP afin de modifier un fichier de configuration et d'exécuter un script.



== Connectez-vous au système de classification BlueXP

Lorsque la classification BlueXP est installée sur une machine Linux de votre site ou sur une machine Linux que vous avez déployée dans le cloud, vous pouvez accéder directement au fichier de configuration et au script.

Lorsque la classification BlueXP est déployée dans le cloud, vous devez établir une connexion SSH avec l'instance de classification BlueXP. Vous vous SSH dans le système en saisissant l'utilisateur et le mot de passe, ou en utilisant la clé SSH fournie lors de l'installation du connecteur BlueXP. La commande SSH est :

 ssh -i <path_to_the_ssh_key> <machine_user>@<datasense_ip>
* <path_to_the_ssh_key> = emplacement des clés d'authentification ssh
* <machine_utilisateur> :
+
** Pour AWS : utilisez <utilisateur ec2>
** Pour Azure : utilisez l'utilisateur créé pour l'instance BlueXP
** Pour GCP : utilisez l'utilisateur créé pour l'instance BlueXP


* <dataense_ip> = adresse IP de l'instance de la machine virtuelle


Notez que vous devrez modifier les règles entrantes du groupe de sécurité pour accéder au système dans le cloud. Pour plus de détails, voir :

* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-aws.html["Règles de groupe de sécurité dans AWS"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html["Règles de groupe de sécurité dans Azure"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-gcp.html["Règles de pare-feu dans Google Cloud"^]




== Ajoutez l'autorisation « Ouvrir à l'organisation » aux ID de groupe

Vous devez disposer des numéros d'ID de groupe (GID) avant de commencer cette tâche.

.Étapes
. Sur le système de classification BlueXP, accédez à «/opt/netapp/config/custom_configuration » et ouvrez le fichier « data_Provider.yaml ».
. Dans la ligne « id_groupe_organisation : [] », ajoutez les ID de groupe. Par exemple :
+
 organization_group_ids: [1014, 1015, 21, 2021, 1013, 2020, 1018, 1019]
+
Ne modifiez rien d'autre dans ce fichier.

. Accédez à « /opt/netapp/Datasense/Tools/customer_configuration/Data_providers » et exécutez le script suivant :
+
 update_data_providers_from_config_file.sh
+
Cette commande valide les autorisations d'ID de groupe révisées au moteur de classification.



Toutes les analyses ultérieures de vos données permettront d'identifier les fichiers ou dossiers auxquels ces ID de groupe sont associés comme « ouverts à l'organisation ».

Vous pouvez modifier la liste des ID de groupe et supprimer les ID de groupe que vous avez ajoutés par le passé en procédant de la même manière. La liste révisée des ID de groupe sera mise à jour après l'exécution du script pour valider vos modifications.

Pour afficher la liste actuelle des ID de groupe que vous avez ajoutés à la classification BlueXP, exécutez la commande suivante depuis « /opt/netapp/Datase/Tools/customer_configuration/data_providers » :

 get_data_providers_configuration.sh