---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, cloud compliance access, compliance, on-premises, linux, test linux system 
summary: 'Avant d"installer Data Sense manuellement sur un hôte Linux, vous pouvez exécuter un script sur l"hôte afin de vérifier que toutes les conditions requises pour l"installation de Data Sense sont en place. Vous pouvez exécuter ce script sur un hôte Linux de votre réseau ou sur un hôte Linux du cloud. L"hôte peut être connecté à Internet, ou l"hôte peut résider sur un site qui n"a pas accès à Internet.' 
---
= Vérifiez que votre hôte Linux est prêt à installer Data Sense
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant d'installer Data Sense manuellement sur un hôte Linux, vous pouvez exécuter un script sur l'hôte afin de vérifier que toutes les conditions requises sont en place pour l'installation de Data Sense. Vous pouvez exécuter ce script sur un hôte Linux de votre réseau ou sur un hôte Linux du cloud. L'hôte peut être connecté à Internet, ou l'hôte peut résider sur un site qui n'a pas accès à Internet (un « site invisible »).

Il existe également un script de test prérequis qui fait partie du script d'installation de Data Sense. Le script décrit ici est spécialement conçu pour les utilisateurs qui souhaitent vérifier l'hôte Linux indépendamment de l'exécution du script d'installation de Data Sense.



== Mise en route

Vous effectuerez les tâches suivantes.

. Facultatif. Installez un connecteur BlueXP si vous n'en avez pas déjà installé. Vous pouvez exécuter le script de test sans avoir installé de connecteur, mais le script vérifie la connectivité entre le connecteur et la machine hôte Data Sense. Il est donc recommandé de disposer d'un connecteur.
. Préparer le porteur et vérifier qu'il répond à toutes les exigences.
. Activez l'accès Internet sortant à partir de la machine hôte Data Sense.
. Vérifiez que tous les ports requis sont activés sur tous les systèmes.
. Téléchargez et exécutez le script de test requis.




== Créer un connecteur

Un connecteur BlueXP est nécessaire avant de pouvoir installer et utiliser Data Sense. Vous pouvez cependant exécuter le script Prerequisites sans connecteur.

C'est possible https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-on-prem.html["Installer le connecteur sur site"^] Sur un hôte Linux de votre réseau ou sur un hôte Linux du cloud. Certains utilisateurs qui prévoient d'installer Data Sense sur site peuvent également choisir d'installer le connecteur sur site.

Pour créer un connecteur dans l'environnement de votre fournisseur de cloud, reportez-vous à la section https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-aws.html["Création d'un connecteur dans AWS"^], https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-azure.html["Création d'un connecteur dans Azure"^], ou https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-connector-google.html["Création d'un connecteur dans GCP"^].

Vous aurez besoin de l'adresse IP ou du nom d'hôte du système de connecteur lors de l'exécution du script Prerequisites. Vous aurez ces informations si vous avez installé le connecteur sur votre site. Si le connecteur est déployé dans le cloud, vous pouvez trouver ces informations à partir de la console BlueXP : cliquez sur l'icône aide, sélectionnez *support* et cliquez sur *BlueXP Connector*.



== Vérifiez les besoins de l'hôte

Le logiciel de détection des données doit être exécuté sur un hôte qui répond à des exigences spécifiques du système d'exploitation, de la RAM, des exigences logicielles, etc.

* Data Sense n'est pas pris en charge sur un hôte partagé avec d'autres applications ; l'hôte doit être un hôte dédié.


* Lors de la création du système hôte sur votre site, vous pouvez choisir entre trois tailles de système en fonction de la taille du jeu de données que vous prévoyez d'utiliser pour l'analyse Data Sense.
+
[cols="18,18,26,30"]
|===
| Taille du système | CPU | RAM (la mémoire d'échange doit être désactivée) | Disque 


| *Grand* | 16 processeurs | 64 GO DE RAM | 500 Gio de SSD sur /, ou - 100 Gio disponible sur /opt - 395 Gio disponible sur /var - 5 Gio sur /tmp 


| *Moyen* | 8 processeurs | 32 GO DE RAM | 200 Gio de SSD sur /, ou - 50 Gio disponible sur /opt - 145 Gio disponible sur /var - 5 Gio sur /tmp 


| *Petit* | 8 processeurs | 16 GO DE RAM | 100 Gio de SSD sur /, ou - 50 Gio disponible sur /opt - 45 Gio disponible sur /var - 5 Gio sur /tmp 
|===
+
Notez qu'il existe des limites lors de l'utilisation de ces systèmes plus petits. Voir link:concept-cloud-compliance.html#using-a-smaller-instance-type["Utilisation d'un type d'instance plus petit"] pour plus d'informations.

* Lors du déploiement d'une instance cloud pour votre installation Data Sense, nous recommandons un système qui répond à la « grande » configuration requise ci-dessus :
+
** *Type d'instance AWS EC2*: Nous recommandons "m6i.4xlarge". link:reference-instance-types.html#aws-instance-types["Consultez la section autres types d'instances AWS"^].
** *Taille de VM Azure*: Nous recommandons "Standard_D16s_v3". link:reference-instance-types.html#azure-instance-types["Consultez la section autres types d'instances Azure"^].
** *Type de machine GCP*: Nous recommandons "n2-standard-16". link:reference-instance-types.html#gcp-instance-types["Voir autres types d'instances GCP"^].


* *Système d'exploitation* : Red Hat Enterprise Linux ou CentOS versions 8.0 à 8.7
+
** CentOS Stream 8 est également pris en charge
** La version 7.8 ou 7.9 peut être utilisée, mais la version du noyau Linux doit être 4.0 ou supérieure
** Le système d'exploitation doit pouvoir installer le moteur docker


* *Gestion des abonnements Red Hat* : un système Red Hat Enterprise Linux doit être enregistré auprès de la gestion des abonnements Red Hat. S'il n'est pas enregistré, le système ne peut pas accéder aux référentiels pour mettre à jour les logiciels tiers requis au cours de l'installation.
* *Logiciel supplémentaire*: Vous devez installer le logiciel suivant sur l'hôte avant d'installer Data Sense:
+
** Docker Engine version 19.3.1 ou ultérieure. https://docs.docker.com/engine/install/["Voir les instructions d'installation"^].
** Python 3 version 3.6 ou ultérieure. https://www.python.org/downloads/["Voir les instructions d'installation"^].


* *Firesund considérations*: Si vous prévoyez d'utiliser `firewalld`, Nous vous recommandons de l'activer avant d'installer Data Sense. Exécutez les commandes suivantes pour configurer `firewalld` Pour qu'il soit compatible avec Data Sense :
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
Si vous prévoyez d'utiliser des hôtes Data Sense supplémentaires en tant que nœuds scanner (dans un modèle distribué), ajoutez ces règles à votre système principal à ce stade :

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
Si vous activez `firewalld` Après avoir installé Data Sense, vous devez redémarrer docker.





== Activez l'accès Internet sortant à partir de Data Sense

Data Sense requiert un accès Internet sortant. Si votre réseau virtuel ou physique utilise un serveur proxy pour l'accès à Internet, assurez-vous que l'instance de détection de données dispose d'un accès Internet sortant pour contacter les points de terminaison suivants.

CONSEIL:: Cette section n'est pas requise pour les systèmes hôtes installés sur des sites sans connexion Internet.


[cols="43,57"]
|===
| Terminaux | Objectif 


| \https://api.bluexp.netapp.com | Communication avec le service BlueXP, qui inclut les comptes NetApp. 


| \https://netapp-cloud-account.auth0.com \https://auth0.com | Communication avec le site Web BlueXP pour l'authentification centralisée des utilisateurs. 


| \https://support.compliance.api.bluexp.netapp.com/ \https://hub.docker.com \https://auth.docker.io \https://registry-1.docker.io \https://index.docker.io/ \https://dseasb33srnrn.cloudfront.net/ \https://production.cloudflare.docker.com/ | Permet d'accéder aux images logicielles, aux manifestes, aux modèles et à l'envoi de journaux et de mesures. 


| \https://support.compliance.api.bluexp.netapp.com/ | Permet à NetApp de diffuser des données à partir d'enregistrements d'audit. 


| \https://github.com/docker \https://download.docker.com \http://mirror.centos.org \http://mirrorlist.centos.org \http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm | Fournit les packages requis pour l'installation. 
|===


== Vérifiez que tous les ports requis sont activés

Vous devez vous assurer que tous les ports requis sont ouverts pour la communication entre le connecteur, Data Sense, Active Directory et vos sources de données.

[cols="25,25,50"]
|===
| Type de connexion | Ports | Description 


| Connecteur <> détection des données | 8080 (TCP), 443 (TCP) et 80 | Le pare-feu ou les règles de routage du connecteur doivent autoriser le trafic entrant et sortant via le port 443 vers et depuis l'instance de détection des données. Assurez-vous que le port 8080 est ouvert pour voir la progression de l'installation dans BlueXP. 


| Connecteur <> cluster ONTAP (NAS) | 443 (TCP)  a| 
BlueXP détecte les clusters ONTAP via HTTPS. Si vous utilisez des stratégies de pare-feu personnalisées, l'hôte du connecteur doit autoriser l'accès HTTPS sortant via le port 443. Si le connecteur est dans le cloud, toutes les communications sortantes sont autorisées par le pare-feu ou les règles de routage prédéfinies.

|===


== Exécutez le script Data Sense Prerequisites

Procédez comme suit pour exécuter le script Data Sense Prerequisites.

.Ce dont vous avez besoin
* Vérifiez que votre système Linux est conforme à la <<Vérifiez les besoins de l'hôte,configuration requise pour l'hôte>>.
* Assurez-vous que les deux packages logiciels prérequis du système sont installés (Docker Engine et Python 3).
* Assurez-vous que vous disposez des privilèges root sur le système Linux.


.Étapes
. Téléchargez le script Data Sense Prerequisites à partir du https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["Site de support NetApp"^]. Le fichier que vous devez sélectionner est nommé *test_datasense_prerequisites_<version>*.
. Copiez le fichier sur l'hôte Linux que vous souhaitez utiliser (à l'aide de `scp` ou une autre méthode).
. Attribuez des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x test_datasense_prerequisites_1_0
----
. Exécutez le script à l'aide de la commande suivante.
+
./test_datasense_prerequisites_1_0 &#8592;-darksite>
[source, cli]
----
Add the option "--darksite" only if you are running the script on a host that doesn't have internet access. Certain prerequisite tests are skipped when the host is not connected to the internet.
----
. Le script vous demande l'adresse IP de la machine hôte Data Sense.
+
** Entrez l'adresse IP ou le nom d'hôte.


. Le script vous demande si BlueXP Connector est installé.
+
** Entrez *N* si vous n'avez pas de connecteur installé.
** Entrez *y* si vous avez un connecteur installé. Puis entrez l'adresse IP ou le nom d'hôte du connecteur BlueXP afin que le script de test puisse tester cette connectivité.


. Le script exécute une variété de tests sur le système et affiche les résultats au fur et à mesure qu'il progresse. Une fois terminé, il écrit un journal de la session dans un fichier.


.Résultat
Si tous les tests préalables ont été exécutés avec succès, vous pouvez installer Data Sense sur l'hôte lorsque vous êtes prêt.

Si des problèmes ont été découverts, ils sont classés comme « recommandés » ou « obligatoires » pour être résolus. Les problèmes recommandés sont généralement des éléments qui ralentiraient l'exécution des tâches d'acquisition et de catégorisation de Data Sense. Ces éléments n'ont pas besoin d'être corrigés, mais vous pouvez les corriger.

Si vous rencontrez des problèmes « obligatoires », vous devez résoudre les problèmes et exécuter à nouveau le script de test prérequis.
