---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: Découvrez les nouveautés du Cloud Data sens. 
---
= Quelles sont les nouveautés du cloud Data
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés du Cloud Data sens.



== 3 avril 2023 (version 1.22)



=== Nouveau rapport d'évaluation de découverte de données

Le rapport d'évaluation de la découverte de données fournit une analyse de haut niveau de votre environnement analysé afin de mettre en évidence les résultats du système et de montrer les points préoccupants et les étapes de correction potentielles. L'objectif de ce rapport est de sensibiliser les clients aux préoccupations liées à la gouvernance des données, à l'exposition aux risques en matière de sécurité des données et aux lacunes de conformité de leurs jeux de données. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-discovery-assessment-report["Découvrez comment générer et utiliser le rapport d'évaluation de découverte de données"].



=== Possibilité de déployer Data Sense sur des instances plus petites dans le cloud

Lors du déploiement de Data Sense à partir d'un connecteur BlueXP dans un environnement AWS, vous pouvez désormais choisir entre deux types d'instances plus petits que ceux disponibles avec l'instance par défaut. Si vous analysez un petit environnement, vous pouvez réduire vos coûts liés au cloud. Cependant, il existe des restrictions lors de l'utilisation de la plus petite instance. https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html#using-a-smaller-instance-type["Voir les types d'instances et les limites disponibles"].



=== Un script autonome est désormais disponible pour vérifier que votre système Linux est qualifié pour installer Data Sense

Si vous souhaitez vérifier que votre système Linux remplit toutes les conditions requises indépendamment de l'exécution de l'installation de Data Sense, vous pouvez télécharger un script distinct qui ne teste que les conditions préalables. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-test-linux-system.html["Découvrez comment vérifier si votre hôte Linux est prêt à installer Data Sense"].



=== Les licences Data Sense BYOL sont désormais prises en charge sur les sites invisibles

Vous pouvez désormais télécharger votre licence Data Sense BYOL dans le portefeuille digital, dans un site invisible, pour être averti lorsque le niveau de licence est faible. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-licensing-datasense.html#obtain-your-cloud-data-sense-license-file["Découvrez comment obtenir et télécharger votre licence Data Sense BYOL"].



== 7 mars 2023 (version 1.21)



=== Nouvelle fonctionnalité permettant d'ajouter vos propres catégories personnalisées à partir de l'interface utilisateur Data Sense

Data Sense vous permet désormais d'ajouter vos propres catégories personnalisées afin que Data Sense identifie les fichiers qui correspondent à ces catégories. Data Sense en a beaucoup https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-categories["catégories prédéfinies"], cette fonction vous permet d'ajouter des catégories personnalisées pour identifier l'endroit où les informations propres à votre organisation se trouvent dans vos données.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-categories["En savoir plus >>"^].



=== Vous pouvez maintenant ajouter des mots clés personnalisés à partir de l'interface utilisateur Data Sense

Data Sense a eu la possibilité d'ajouter des mots clés personnalisés que Data Sense identifiera dans les analyses futures pendant un certain temps. Cependant, vous devez vous connecter à l'hôte Data Sense Linux et utiliser une interface de ligne de commande pour ajouter les mots clés. Dans cette version, la possibilité d'ajouter des mots-clés personnalisés se trouve dans l'interface utilisateur Data Sense, ce qui facilite l'ajout et la modification de ces mots-clés.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["En savoir plus sur l'ajout de mots-clés personnalisés à partir de l'interface utilisateur Data Sense"^].



=== Possibilité d'avoir des fichiers d'analyse de Data Sense *NOT* lorsque l'heure du dernier accès sera modifiée

Par défaut, si Data Sense ne dispose pas des autorisations d'écriture adéquates, le système n'analyse pas les fichiers de vos volumes, car Data Sense ne peut pas rétablir l'heure du dernier accès à l'heure d'origine. Cependant, si vous ne vous souciez pas de réinitialiser l'heure du dernier accès à l'heure d'origine dans vos fichiers, vous pouvez remplacer ce comportement dans la page Configuration afin que Data Sense analyse les volumes sans tenir compte des autorisations.

Grâce à cette fonctionnalité, et un nouveau filtre nommé « Scan Analysis Event » a été ajouté pour vous permettre d'afficher les fichiers qui n'ont pas été classés car Data Sense n'a pas pu revenir à l'heure du dernier accès, ou les fichiers qui ont été classés même si Data Sense n'a pas pu revenir à l'heure du dernier accès.

https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-collected-metadata.html#last-access-time-timestamp["En savoir plus sur l'horodatage du dernier accès et les autorisations requises par Data Sense"].



=== Data Sense identifie trois nouveaux types de données personnelles

Data Sense peut identifier et catégoriser les fichiers contenant les types de données suivants :

* Numéro de carte d'identité Botswana (Omang)
* Botswana Numéro de passeport
* Carte d'identité nationale d'enregistrement de Singapour (NRIC)


https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["Consultez tous les types de données personnelles que Data Sense peut identifier dans vos données"].



=== Mise à jour des fonctionnalités des répertoires

* L'option « Rapport CSV léger » pour les rapports d'investigation de données inclut désormais des informations provenant des répertoires.
* Le filtre heure « dernier accès » affiche désormais l'heure du dernier accès pour les fichiers et les répertoires.




=== Améliorations apportées à l'installation

* Data Sense peut être installé sur des hôtes Linux qui exécutent CentOS Stream 8.
* Le programme d'installation de Data Sense pour les sites sans accès à Internet (sites invisibles) effectue désormais un pré-contrôle pour s'assurer que vos exigences système et réseau sont en place pour une installation réussie.
* Les fichiers journaux d'audit d'installation sont enregistrés maintenant ; ils sont écrits dans `/ops/netapp/install_logs`.




== 5 février 2023 (version 1.20)



=== Possibilité d'envoyer des e-mails de notification basés sur des règles à n'importe quelle adresse e-mail

Dans les versions antérieures de Cloud Data SENSE, vous pouvez envoyer des alertes par e-mail aux utilisateurs BlueXP de votre compte lorsque certaines stratégies critiques renvoient des résultats. Cette fonction vous permet d'obtenir des notifications pour protéger vos données lorsque vous n'êtes pas en ligne. Vous pouvez désormais envoyer des alertes par e-mail à partir de stratégies à tous les autres utilisateurs - jusqu'à 20 adresses e-mail - qui ne sont pas dans votre compte BlueXP.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["En savoir plus sur l'envoi d'alertes par e-mail basées sur les résultats des règles"].



=== Vous pouvez désormais ajouter des modèles personnels à partir de l'interface utilisateur de Data Sense

Data Sense a la possibilité d'ajouter des « données personnelles » personnalisées que Data Sense identifiera pendant un certain temps dans les futures analyses. Cependant, vous devez vous connecter à l'hôte Data Sense Linux et utiliser une ligne de commande pour ajouter les modèles personnalisés. Dans cette version, la possibilité d'ajouter des motifs personnels à l'aide d'un regex se trouve dans l'interface utilisateur de Data Sense, ce qui facilite l'ajout et la modification de ces modèles personnalisés.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["En savoir plus sur l'ajout de modèles personnalisés à partir de l'interface utilisateur Data Sense"^].



=== Capacité à déplacer 15 millions de fichiers avec Data Sense

Par le passé, il était possible que Data Sense déplace un maximum de 100,000 fichiers source vers n'importe quel partage NFS. Vous pouvez désormais déplacer jusqu'à 15 millions de fichiers à la fois. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["En savoir plus sur le déplacement de fichiers source à l'aide de Data Sense"].



=== Possibilité de voir le nombre d'utilisateurs ayant accès aux fichiers SharePoint Online

Le filtre « nombre d'utilisateurs avec accès » prend désormais en charge les fichiers stockés dans les référentiels SharePoint Online. Auparavant, seuls les fichiers stockés sur des partages CIFS étaient pris en charge. Notez que les groupes SharePoint qui ne sont pas actifs basés sur un répertoire ne seront pas pris en compte dans ce filtre à l'heure actuelle.



=== Le nouvel état « réussite partielle » a été ajouté au panneau État de l'action

Le nouvel état « réussite partielle » indique qu'une action détection de données est terminée et que certains éléments ont échoué et que certains éléments ont réussi, par exemple, lorsque vous déplacez ou supprimez 100 fichiers. De plus, le statut « terminé » a été renommé « succès ». Par le passé, l'état « terminé » peut lister les actions qui ont réussi et qui ont échoué. Désormais, le statut « réussite » signifie que toutes les actions ont réussi sur tous les éléments. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-view-compliance-actions.html["Voir comment afficher le panneau Etat des actions"].



== 9 janvier 2023 (version 1.19)



=== Possibilité d'afficher un graphique de fichiers contenant des données sensibles et qui sont trop permissives

Le tableau de bord gouvernance a ajouté une nouvelle zone données et autorisations larges_ qui fournit une carte thermique de fichiers contenant des données sensibles (y compris des données personnelles sensibles et sensibles) et qui sont trop permissives. Cela vous aide à déterminer les risques liés aux données sensibles. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["En savoir plus >>"].



=== Trois nouveaux filtres sont disponibles dans la page Data Investigation

De nouveaux filtres sont disponibles pour affiner les résultats affichés dans la page recherche de données :

* Le filtre « nombre d'utilisateurs avec accès » indique quels fichiers et dossiers sont ouverts à un certain nombre d'utilisateurs. Vous pouvez choisir une plage de nombres pour affiner les résultats, par exemple pour voir quels fichiers sont accessibles par 51-100 utilisateurs.
* Les filtres « heure créée », « heure découverte », « dernière modification » et « dernier accès » vous permettent désormais de créer une plage de dates personnalisée au lieu de sélectionner une plage de jours prédéfinie. Par exemple, vous pouvez rechercher des fichiers avec une "heure de création" "plus de 6 mois", ou avec une "date de dernière modification" dans les "10 derniers jours".
* Le filtre "chemin du fichier" vous permet maintenant de spécifier les chemins que vous souhaitez exclure des résultats de la requête filtrée. Si vous entrez des chemins pour inclure et exclure certaines données, Data Sense recherche d'abord tous les fichiers des chemins inclus, puis supprime les fichiers des chemins exclus, puis affiche les résultats.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-investigate-data.html#filtering-data-in-the-data-investigation-page["Voir la liste de tous les filtres que vous pouvez utiliser pour examiner vos données"].



=== Le capteur de données peut identifier le numéro individuel japonais

Data Sense peut identifier et classer les fichiers contenant le numéro individuel japonais (également appelé mon numéro). Cela inclut à la fois le numéro mon personnel et celui de l'entreprise. https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["Consultez tous les types de données personnelles que Data Sense peut identifier dans vos données"].



== 11 décembre 2022 (version 1.18)



=== Améliorations apportées à l'installation sur site

Plusieurs améliorations ont été ajoutées à l'installation de Data Sense sur site :

* Certaines conditions préalables supplémentaires sont maintenant vérifiées avant que l'installation ne démarre sur un hôte sur site. Ainsi, vous vous assurez que votre système hôte est 100 % prêt à installer le logiciel Data Sense :
+
** vérifiez que l'espace disponible est suffisant `/var/lib/docker`, `/tmp`, et `/opt`
** testez les autorisations pertinentes sur tous les dossiers requis


* Dans la page Configuration, la section environnements de travail affiche maintenant le _ID de l'environnement de travail_ et le _scanner Group_ name. Vous devrez connaître l'ID de l'environnement de travail si vous prévoyez d'utiliser plusieurs hôtes Data Sense pour fournir une puissance de traitement supplémentaire pour analyser vos sources de données.
* La page Configuration affiche également les groupes de scanners que vous avez configurés et les nœuds de scanner de chaque groupe.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html["En savoir plus sur l'installation de Data Sense sur un serveur hôte unique et sur plusieurs hôtes"].



== 13 novembre 2022 (version 1.17)



=== Prise en charge de la numérisation des comptes SharePoint sur site

Il est désormais possible d'analyser les comptes SharePoint Online et les comptes SharePoint sur site (SharePoint Server). Si vous devez installer SharePoint sur vos propres serveurs ou sur des sites sans accès à Internet, vous pouvez maintenant avoir Data Sense scan les fichiers utilisateur dans ces comptes. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["En savoir plus >>"^].



=== Possibilité de réanalyser plusieurs répertoires (dossiers ou partages)

Vous pouvez désormais analyser plusieurs répertoires (dossiers ou partages) immédiatement afin que les modifications soient répercutées dans le système. Cela vous permet de hiérarchiser la réanalyse de certaines données avant d'autres données. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Voir la procédure de nouvelle analyse d'un répertoire"^].



=== Possibilité d'ajouter des nœuds de numérisation supplémentaires sur site pour analyser des sources de données spécifiques

Si vous avez installé Data SENSE sur site et que vous avez besoin d'une puissance de traitement plus élevée pour analyser certaines sources de données, vous pouvez ajouter d'autres nœuds de « scanner » et les affecter pour analyser ces sources de données. Vous pouvez ajouter les nœuds du scanner immédiatement après avoir installé le nœud du gestionnaire, ou vous pouvez ajouter un nœud du scanner ultérieurement.

Si nécessaire, les nœuds du scanner peuvent être installés sur des systèmes hôtes qui sont physiquement plus proches des sources de données que vous scannez. Plus le nœud du scanner est proche des données, mieux c'est, car il réduit la latence du réseau autant que possible lors de l'acquisition des données. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["Découvrez comment installer des nœuds de scanner pour analyser d'autres sources de données"^].



=== Les installateurs sur site effectuent désormais une pré-vérification avant de commencer l'installation

Lors de l'installation de Data Sense sur un système Linux, le programme d'installation vérifie si le système répond à toutes les exigences nécessaires (CPU, RAM, capacité, réseau, etc.) avant de démarrer l'installation. Cela permet de détecter les problèmes *avant*, vous passez du temps sur l'installation.



== 6 septembre 2022 (version 1.16)



=== Possibilité de réanalyser immédiatement un référentiel pour refléter les modifications apportées aux fichiers

Si vous devez relancer une nouvelle analyse d'un référentiel particulier immédiatement afin que les modifications soient répercutées dans le système, vous pouvez sélectionner le référentiel et le relancer. Cela vous permet de hiérarchiser la réanalyse de certaines données avant d'autres données. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Voir la procédure de nouvelle analyse d'un répertoire"^].



=== Nouveau filtre pour l'état de l'acquisition de détection de données dans la page recherche de données

Le filtre "Etat de l'analyse" vous permet de répertorier les fichiers qui se trouvent dans une étape spécifique de l'analyse de détection de données. Vous pouvez sélectionner une option pour afficher la liste des fichiers qui sont *en attente première numérisation*, *terminé* en cours de numérisation, *en attente de numérisation* ou dont *échoué* doit être scanné.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Voir la liste de tous les filtres que vous pouvez utiliser pour examiner vos données"^].



=== Les sujets de données sont désormais considérés comme faisant partie des « données personnelles » trouvées dans les acquisitions

Data Sense reconnaît maintenant les sujets de données dans le cadre des résultats personnels qui apparaissent dans le tableau de bord de conformité. En outre, lorsque vous effectuez une recherche dans la page Investigation, vous pouvez sélectionner « sujets de données » sous « données personnelles » pour afficher uniquement les fichiers contenant des données.



=== Les fichiers de navigation de détection de données sont désormais considérés comme faisant partie des « catégories » trouvées dans les scans

Data Sense reconnaît maintenant des fichiers de navigation dans les catégories qui apparaissent dans le Tableau de bord de conformité. Il s'agit de fichiers que Data Sense crée lors du déplacement des fichiers de l'emplacement source vers un partage NFS. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Découvrez comment créer des fichiers de navigation"^].

De plus, lorsque vous effectuez une recherche dans la page Investigation, vous pouvez sélectionner « fil d'Ariane de détection des données » sous « Catégorie » pour afficher uniquement les fichiers de navigation de détection des données.



== 7 août 2022 (version 1.15)



=== Cinq nouveaux types de données personnelles de la Nouvelle-Zélande sont identifiés par Data Sense

Data Sense peut identifier et catégoriser les fichiers contenant les types de données suivants :

* Numéro de compte bancaire de la Nouvelle-Zélande
* Numéro de permis de conduire de la Nouvelle-Zélande
* Numéro IRD de Nouvelle-Zélande (ID taxe)
* Numéro NHI (National Health Index) de la Nouvelle-Zélande
* Numéro de passeport de la Nouvelle-Zélande


link:reference-private-data-categories.html#types-of-personal-data["Consultez tous les types de données personnelles que Data Sense peut identifier dans vos données"].



=== Possibilité d'ajouter un fichier de navigation pour indiquer pourquoi un fichier a été déplacé

Lorsque vous utilisez la fonction détection de données pour déplacer les fichiers source vers un partage NFS, vous pouvez maintenant laisser un fichier de navigation à l'emplacement du fichier déplacé. Un fichier de navigation permet à vos utilisateurs de comprendre pourquoi un fichier a été déplacé de son emplacement d'origine. Pour chaque fichier déplacé, le système crée un fichier de navigation à l'emplacement source nommé `<filename>-breadcrumb-<date>.txt` pour afficher l'emplacement où le fichier a été déplacé et l'utilisateur qui a déplacé le fichier. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["En savoir plus >>"^].



=== Les données personnelles et les données personnelles sensibles contenues dans vos répertoires sont affichées dans les résultats de l'enquête

La page Data Investigation affiche maintenant les résultats des données personnelles et des données personnelles sensibles trouvées dans vos répertoires (dossiers et partages). https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-files-that-contain-personal-data["Voir un exemple ici"^].



=== Afficher l'état du nombre de volumes, de compartiments, etc. Classés

Lorsque vous visualisez les différents référentiels, Data Sense est analyse (volumes, compartiments, etc.), vous pouvez maintenant voir combien d'entre eux ont été « mappés » et combien d'entre eux ont été « classés ». Le classement est plus long lorsque l'identification complète de l'IA est effectuée sur toutes les données. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["Voir comment afficher ces informations"^].



=== Vous pouvez maintenant ajouter des modèles personnalisés que Data Sense identifie dans vos données

Il existe deux façons d'ajouter des « données personnelles » personnalisées que Data Sense identifiera dans les analyses futures. Vous disposez ainsi d'une vision globale de l'emplacement des données potentiellement sensibles dans les fichiers de votre entreprise.

* Vous pouvez ajouter des mots-clés personnalisés à partir d'un fichier texte.
* Vous pouvez ajouter un motif personnel à l'aide d'une expression régulière (regex).


Ces mots-clés et modèles sont ajoutés aux modèles prédéfinis existants que Data Sense utilise déjà et les résultats seront visibles sous la section modèles personnels. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html["En savoir plus >>"^].



== 6 juillet 2022 (version 1.14)



=== Vous pouvez maintenant afficher les utilisateurs et les groupes qui ont accès à vos répertoires

Auparavant, vous pouviez afficher les types d'autorisations ouvertes accordées sur des fichiers individuels. Vous pouvez maintenant afficher une liste de tous les utilisateurs ou groupes qui ont accès aux répertoires (dossiers et partages de fichiers) et aux types d'autorisations dont ils disposent. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["Découvrez comment afficher les utilisateurs et les groupes qui ont accès à vos dossiers et partages de fichiers"].



=== Vous pouvez « suspendre » la numérisation d'un référentiel pour arrêter temporairement la numérisation de certains contenus

La mise en pause de l'acquisition signifie que Data SENSE n'effectue pas d'acquisition ultérieure sur tout ajout ou modification d'un volume ou d'un compartiment, mais que tous les résultats actuels seront toujours disponibles dans le système. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["Découvrez comment interrompre et reprendre l'acquisition"].



=== Les données RELATIVES aux licences de conducteur DES ÉTATS-UNIS provenant de trois États supplémentaires peuvent être identifiées par Data Sense

Data Sense peut identifier et classer les fichiers contenant les données de licence du conducteur de l'Indiana, de New York et du Texas. link:reference-private-data-categories.html#types-of-personal-data["Consultez tous les types de données personnelles que Data Sense peut identifier dans vos données"].



=== Les stratégies renvoient maintenant des répertoires qui correspondent aux critères de recherche

Auparavant, lorsque vous avez créé une stratégie personnalisée, les résultats ont montré les fichiers correspondant aux critères de recherche. Les résultats affichent également les répertoires (dossiers et partages de fichiers) correspondant à la requête. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#creating-custom-policies["En savoir plus sur la création de règles"].



=== « Data Sense » peut déplacer jusqu'à 100,000 fichiers à la fois

Si vous prévoyez d'utiliser Data Sense pour déplacer des fichiers d'une source de données numérisée vers un partage NFS, le nombre maximum de fichiers a été porté à 100,000 fichiers. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Découvrez comment déplacer des fichiers à l'aide de Data Sense"].



== 12 juin 2022 (version 1.13.1)



=== Vous pouvez maintenant télécharger les résultats à partir de la page Data Investigation sous forme de rapport .JSON

Une fois les données filtrées dans la page Data Investigation, vous pouvez maintenant enregistrer les données en tant que rapport dans un fichier .JSON que vous pouvez exporter vers un partage NFS, en plus d'enregistrer les données dans un fichier .CSV sur votre système local. Assurez-vous que Data Sense dispose des autorisations appropriées pour l'accès à l'exportation. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-generating-compliance-reports.html#data-investigation-report["Voir comment créer des rapports à partir de la page recherche de données"].



=== Possibilité de désinstaller Data Sense à partir de l'interface utilisateur Data Sense

Vous pouvez désinstaller Data Sense pour supprimer définitivement le logiciel de l'hôte et, dans le cas d'un déploiement cloud, supprimer la machine virtuelle/l'instance sur laquelle Data Sense a été déployé. La suppression de l'instance supprime définitivement toutes les informations indexées que le sens des données a numérisées. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-uninstall-data-sense.html["Découvrez comment"].



=== La journalisation des audits est désormais disponible pour suivre l'historique des actions réalisées par Data Sense

Le journal d'audit assure le suivi des activités de gestion que Data Sense a effectuées sur les fichiers de tous les environnements de travail et les sources de données que Data Sense est en train d'analyser. Les activités peuvent être générées par l'utilisateur (suppression d'un fichier, création d'une stratégie, etc.) ou générées (ajout automatique d'étiquettes aux fichiers, suppression automatique des fichiers, etc.).

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-audit-data-sense-actions.html["Voir plus de détails sur le journal d'audit"].



=== Nouveau filtre pour le nombre d'identificateurs sensibles dans la page recherche de données

Le filtre “nombre d’identificateurs” permet de répertorier les fichiers qui ont un certain nombre d’identificateurs sensibles, y compris les données personnelles et les données personnelles sensibles. Vous pouvez sélectionner une plage telle que 1-10 ou 501-1000 pour afficher uniquement les fichiers qui contiennent ce nombre d'identificateurs sensibles.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Voir la liste de tous les filtres que vous pouvez utiliser pour examiner vos données"].



=== Vous pouvez maintenant modifier les stratégies existantes que vous avez créées

Si vous devez modifier une règle personnalisée que vous avez créée auparavant, vous pouvez maintenant la modifier au lieu de créer une nouvelle stratégie. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#editing-policies["Voir comment modifier une stratégie"].



== 11 mai 2022 (version 1.12.1)



=== Prise en charge ajoutée pour la numérisation de données dans les comptes Google Drive

Vous pouvez maintenant ajouter vos comptes Google Drive à Data Sense afin de numériser les documents et les fichiers à partir de ces comptes Google Drive. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-google-drive.html["Découvrez comment numériser vos comptes Google Drive"].

Data Sense peut identifier les informations personnelles identifiables (PII) dans les types de fichiers Google suivants à partir de la suite Google Docs -- Docs, Sheets et Slides -- en plus de https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-files["types de fichiers existants"].



=== Affichage au niveau du répertoire ajouté à la page Data Investigation

Outre l'affichage et le filtrage des données de tous vos fichiers et bases de données, vous pouvez maintenant afficher et filtrer les données en fonction de toutes les données contenues dans les dossiers et les partages de la page recherche de données. Les répertoires seront indexés pour les partages CIFS et NFS analysés, ainsi que pour les dossiers OneDrive, SharePoint et Google Drive. Désormais, vous pouvez afficher les autorisations et gérer vos données au niveau du répertoire. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Découvrez comment sélectionner la vue répertoires de vos données numérisées"].



=== Développez groupes pour afficher les utilisateurs/membres qui ont des autorisations d'accès à un fichier

Dans le cadre des fonctions d'autorisations Data Sense, vous pouvez maintenant afficher la liste des utilisateurs et groupes qui ont accès à un fichier. Chaque groupe peut être développé pour afficher la liste des utilisateurs du groupe. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files["Découvrez comment afficher les utilisateurs et les groupes qui ont des autorisations de lecture et/ou d'écriture sur vos fichiers"].



=== Deux nouveaux filtres ont été ajoutés à la page recherche de données

* Le filtre "Type de répertoire" vous permet de raffiner vos données pour afficher uniquement les dossiers ou les partages. Les résultats s'afficheront dans le nouvel onglet *répertoires*.
* Le filtre « autorisations utilisateur/groupe » vous permet de répertorier les fichiers, dossiers et partages auxquels un utilisateur ou un groupe possède des autorisations de lecture et/ou d'écriture. Vous pouvez sélectionner plusieurs utilisateurs et/ou noms de groupe ou entrer un nom partiel.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Voir la liste de tous les filtres que vous pouvez utiliser pour examiner vos données"].



== 5 avril 2022 (version 1.11.1)



=== Quatre nouveaux types de données personnelles australiennes peuvent être identifiés par Data Sense

Data Sense peut identifier et classer les fichiers contenant le TFN australien (Numéro de dossier fiscal), le numéro de permis de conduire australien, le numéro d'assurance-maladie australien et le numéro de passeport australien. link:reference-private-data-categories.html#types-of-personal-data["Consultez tous les types de données personnelles que Data Sense peut identifier dans vos données"].



=== Le serveur Active Directory global peut maintenant être un serveur LDAP

Le serveur Active Directory global que vous intégrez à Data Sense peut désormais être un serveur LDAP en plus du serveur DNS pris en charge précédemment. link:task-add-active-directory-datasense.html["Cliquez ici pour plus d'informations"].



== 15 mars 2022 (version 1.10.0)



=== Nouveau filtre pour afficher les fichiers auxquels un utilisateur ou un groupe a des autorisations de lecture ou d'écriture

Un nouveau filtre appelé « autorisations utilisateur/groupe » a été ajouté pour vous permettre de répertorier les fichiers auxquels un utilisateur ou un groupe a des autorisations de lecture et/ou d'écriture. Vous pouvez sélectionner un ou plusieurs noms d'utilisateur et/ou de groupe ou entrer un nom partiel. Cette fonctionnalité est disponible pour les volumes sur Cloud Volumes ONTAP, ONTAP sur site, Azure NetApp Files, Amazon FSX pour ONTAP et les partages de fichiers.



=== Il permet de déterminer les autorisations pour les fichiers des comptes SharePoint et OneDrive

Il est possible de lire les autorisations existantes pour les fichiers analysés dans les comptes OneDrive et SharePoint. Ces informations s'affichent dans le volet Investigation des détails relatifs aux fichiers et dans la zone Ouvrir les autorisations du tableau de bord de gouvernance.



=== Deux autres types de données personnelles peuvent être identifiés par Data Sense

* INSEE français - le code INSEE est un code numérique utilisé par l'Institut national français de statistique et d'études économiques (INSEE) pour identifier diverses entités.
* Mots de passe : ces informations sont identifiées via la validation de proximité en recherchant les permutations du mot de passe à côté d'une chaîne alphanumérique. Le nombre d'éléments trouvés sera indiqué sous « Résultats personnels » dans le tableau de bord de conformité. Vous pouvez rechercher des fichiers contenant des mots de passe dans le volet Investigation en utilisant le filtre *données personnelles > Mot de passe*.




=== Prise en charge de l'analyse des données OneDrive et SharePoint lorsqu'elles sont déployées sur un site sombre

Lorsque vous avez déployé Cloud Data sur un hôte situé sur un site qui ne dispose pas d'un accès Internet, vous pouvez désormais analyser les données locales à partir des comptes OneDrive ou des comptes SharePoint. link:task-deploy-compliance-dark-site.html#sharepoint-and-onedrive-special-requirements["Vous devez autoriser l'accès aux points de terminaison suivants."]



=== La fonctionnalité bêta permettant d'utiliser Cloud Data Sense pour analyser vos fichiers Cloud Backup a été abandonnée dans cette version



== 9 février 2022



=== Ajout de la prise en charge de la numérisation des comptes en ligne Microsoft SharePoint

Vous pouvez désormais ajouter vos comptes en ligne SharePoint à Data Sense afin de numériser les documents et les fichiers de vos sites SharePoint. link:task-scanning-sharepoint.html["Découvrez comment analyser vos comptes SharePoint"].



=== Data Sense peut copier des fichiers d'une source de données vers un emplacement cible et les synchroniser

Cela est utile dans les situations où vous migrez des données et que vous souhaitez capturer les dernières modifications apportées aux fichiers. Cette action utilise le https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["NetApp Cloud Sync"^] fonctionnalité permettant de copier et de synchroniser les données d'une source vers une cible.

link:task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system["Découvrez comment copier et synchroniser des fichiers"].



=== Prise en charge des nouvelles langues pour les rapports DSAR

L'allemand et l'espagnol sont maintenant pris en charge lors de la recherche de noms de sujets de données afin de créer des rapports DSAR (Data Subject Access Request). Ce rapport est conçu pour aider votre entreprise à respecter le RGPD ou d'autres lois similaires sur la protection des données.



=== Trois autres types de données personnelles peuvent être identifiés par Data Sense

Data Sense peut maintenant trouver des numéros de sécurité sociale en français, des ID en français et des numéros de permis de conduire en français dans les fichiers. link:reference-private-data-categories.html#types-of-personal-data["Consultez la liste de tous les types de données personnelles que Data Sense identifie dans les acquisitions"].



=== Port du groupe de sécurité modifié pour la communication de détection de données vers le connecteur

Le groupe de sécurité du connecteur Cloud Manager utilise le port 443 au lieu du port 80 pour le trafic entrant et sortant vers et depuis l'instance Data Sense pour une sécurité accrue. Les deux ports restent ouverts à ce moment, donc vous ne devriez pas voir de problèmes, mais vous devez mettre à jour le groupe de sécurité dans les déploiements plus anciens du connecteur car le port 80 sera obsolète dans une version ultérieure.
