---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, cloud data sense, bluexp, bluexp classification' 
summary: Découvrez les nouveautés de la classification BlueXP. 
---
= Nouveautés du classement BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de la classification BlueXP.



== 12 mai 2025



=== Version 1.43

Cette version de classification BlueXP  inclut :

.Hiérarchiser les analyses de classification
La classification BlueXP  permet désormais de hiérarchiser les analyses cartographiques et de les classer en plus des acquisitions de mappage uniquement, ce qui vous permet de sélectionner les acquisitions qui sont effectuées en premier. La définition des priorités pour les acquisitions de carte et de classification est prise en charge pendant et avant le début des acquisitions. Si vous choisissez de hiérarchiser une acquisition pendant qu'elle est en cours, les acquisitions de mappage et de classification sont classées par ordre de priorité.

Pour plus d'informations, voir link:task-managing-repo-scanning.html#prioritize-scans["Hiérarchiser les acquisitions"].

.Prise en charge des catégories de données canadiennes d'information à caractère personnel (IIP)
Les analyses de classification BlueXP  identifient maintenant les catégories de données des RP canadiennes pour les renseignements bancaires, le numéro de passeport, le numéro d'assurance sociale, le numéro de permis de conduire et le numéro de carte santé pour toutes les provinces et tous les territoires.

Pour plus d'informations, voir xref:reference-private-data-categories.adoc#types-of-personal-data[Catégories de données personnelles].

.Classification personnalisée (aperçu)
La classification BlueXP  prend désormais en charge les classifications personnalisées pour les analyses Map & Classify. Grâce aux classifications personnalisées, vous pouvez personnaliser les analyses BlueXP  pour capturer des données spécifiques à votre entreprise et garantir leur conformité avec les expressions régulières. Cette fonction est actuellement en aperçu.

Pour plus d'informations, voir xref:task-custom-classification.adoc[Ajouter des classifications personnalisées].

.Onglet recherches enregistrées
L'onglet **politiques** a été renommé xref:task-using-policies.html[**Recherches enregistrées**]. La fonctionnalité est la même.

.Envoyer les événements d'analyse à la chronologie BlueXP 
La classification BlueXP  prend désormais en charge l'envoi d'événements de classification (lorsqu'une analyse est lancée et quand elle se termine) à link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Chronologie BlueXP "^].

.Mises à jour de sécurité
* Le paquet Keras a été mis à jour, atténuant les vulnérabilités (BDSA-2025-0107 et BDSA-2025-1984).
* La configuration des containers Docker a été mise à jour. Le conteneur n'a plus accès aux interfaces réseau de l'hôte pour l'élaboration de paquets réseau bruts. En réduisant les accès inutiles, la mise à jour limite les risques potentiels pour la sécurité.


.Amélioration des performances
Des améliorations de code ont été mises en œuvre pour réduire l'utilisation de la mémoire RAM et améliorer les performances globales de la classification BlueXP .

.Correctifs de bogues
Les bugs ayant provoqué l'échec des analyses StorageGRID, les options de filtre de la page d'enquête ne se chargent pas et l'évaluation de découverte de données ne pouvant pas être téléchargée pour les évaluations de volume élevé ont été corrigés.



== 14 avril 2025



=== Version 1.42

Cette version de classification BlueXP  inclut :

.Balayage en vrac pour les environnements de travail
La classification BlueXP  prend désormais en charge les opérations en bloc pour les environnements de travail. Vous pouvez choisir d'activer les analyses de mappage, d'activer les analyses de mappage et de classification, de désactiver les analyses ou de créer une configuration personnalisée sur l'ensemble des volumes de l'environnement de travail. Si vous effectuez une sélection pour un volume individuel, elle remplace la sélection en bloc. Pour effectuer une opération en bloc, accédez à la page **Configuration** et faites votre sélection.

.Télécharger le rapport d'enquête localement
La classification BlueXP  prend désormais en charge la possibilité de télécharger des rapports d'enquête de données localement pour les afficher dans le navigateur. Si vous choisissez l'option locale, l'investigation de données est uniquement disponible au format CSV et n'affiche que les 10,000 premières lignes de données.

Pour plus d'informations, voir link:task-investigate-data.html#create-the-data-investigation-report["Analysez les données stockées dans votre entreprise avec la classification BlueXP "].



== 10 mars 2025



=== Version 1.41

Cette version de classification BlueXP  inclut des améliorations générales et des correctifs. Elle comprend également :

.État de l'acquisition
La classification BlueXP  suit désormais la progression en temps réel des acquisitions de cartographie et de classification _initial_ sur un volume. Des barres progressives séparées suivent les analyses de cartographie et de classification, présentant un pourcentage du total des fichiers analysés. Vous pouvez également passer le curseur de la souris sur une barre de progression pour afficher le nombre de fichiers analysés et le nombre total de fichiers. Le suivi de l'état de vos analyses permet d'obtenir des informations plus détaillées sur la progression de l'analyse, ce qui vous permet de mieux planifier vos analyses et de comprendre l'allocation des ressources.

Pour afficher l'état de vos acquisitions, accédez à **Configuration** dans la classification BlueXP , puis sélectionnez la **Configuration de l'environnement de travail**. La progression est affichée en ligne pour chaque volume.



== 19 février 2025



=== Version 1.40

Cette version de classification BlueXP  inclut les mises à jour suivantes.

.Prise en charge de RHEL 9.5
Cette version prend en charge Red Hat Enterprise Linux v9.5 en plus des versions précédemment prises en charge. Cela s'applique à toute installation manuelle sur site de la classification BlueXP , y compris les déploiements de sites invisibles.

Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP  version 1.30 ou ultérieure : Red Hat Enterprise Linux version 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 et 9.5.

.Prioriser les acquisitions de mappage uniquement
Lorsque vous effectuez des acquisitions de mappage uniquement, vous pouvez hiérarchiser les acquisitions les plus importantes. Cette fonction vous aide lorsque vous disposez de nombreux environnements de travail et que vous souhaitez vous assurer que les numérisations à haute priorité sont effectuées en premier.

Par défaut, les analyses sont mises en file d'attente en fonction de l'ordre dans lequel elles sont initiées. Avec la possibilité de hiérarchiser les numérisations, vous pouvez désormais déplacer les numérisations vers l'avant de la file d'attente. Plusieurs acquisitions peuvent être classées par ordre de priorité. La priorité est désignée dans un ordre de premier entrée et de premier sortie, ce qui signifie que la première analyse prioritaire se déplace vers l'avant de la file d'attente ; la deuxième analyse prioritaire devient la deuxième dans la file d'attente, etc.

La priorité est accordée une fois. Les nouvelles analyses automatiques des données de mappage sont effectuées dans l'ordre par défaut.

La priorisation est limitée à link:concept-cloud-compliance.html["analyses de mappage uniquement"]; elle n'est pas disponible pour les acquisitions de cartes et de classification.

Pour plus d'informations, voir link:task-managing-repo-scanning.html#prioritize-scans["Hiérarchiser les acquisitions"].

.Réessayez toutes les acquisitions
La classification BlueXP  prend désormais en charge la possibilité de recommencer par lots toutes les acquisitions ayant échoué.

Vous pouvez à présent relancer des acquisitions en mode batch avec la fonction **Réessayer tout**. Si les analyses de classification échouent en raison d'un problème temporaire, tel qu'une panne réseau, vous pouvez réessayer toutes les analyses en même temps à l'aide d'un seul bouton au lieu de les essayer à nouveau individuellement. Les acquisitions peuvent être relancées autant de fois que nécessaire.

Pour réessayer toutes les acquisitions :

. Dans le menu BlueXP  Classification, sélectionnez *Configuration*.
. Pour réessayer toutes les acquisitions ayant échoué, sélectionnez *Réessayer toutes les acquisitions*.


.Amélioration de la précision du modèle de catégorisation
La précision du modèle de machine learning du link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["catégories prédéfinies"] a augmenté de 11 %.



== 22 janvier 2025



=== Version 1.39

Cette version de classification BlueXP  met à jour le processus d'exportation du rapport d'investigation de données. Cette mise à jour d'exportation est utile pour effectuer des analyses supplémentaires sur vos données, créer des visualisations supplémentaires sur les données ou partager les résultats de votre enquête de données avec d'autres personnes.

Auparavant, l'exportation du rapport d'investigation de données était limitée à 10,000 lignes. Avec cette version, la limite a été supprimée afin que vous puissiez exporter toutes vos données. Cette modification vous permet d'exporter davantage de données à partir de vos rapports d'investigation de données, vous offrant ainsi une plus grande flexibilité dans votre analyse de données.

Vous pouvez choisir l'environnement de travail, les volumes, le dossier de destination et le format JSON ou CSV. Le nom de fichier exporté inclut un horodatage qui vous aide à identifier le moment où les données ont été exportées.

Les environnements de travail pris en charge sont les suivants :

* Cloud Volumes ONTAP
* FSX pour ONTAP
* ONTAP
* Partager le groupe


L'exportation de données à partir du rapport d'investigation de données comporte les limites suivantes :

* Le nombre maximum d'enregistrements à télécharger est de 500 millions. Par type (fichiers, répertoires et tables)
* L'exportation d'un million de documents devrait prendre environ 35 minutes.


Pour plus de détails sur l'investigation des données et le rapport, voir https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Analysez les données stockées dans votre entreprise"].



== 16 décembre 2024



=== Version 1.38

Cette version de classification BlueXP  inclut des améliorations générales et des correctifs.



== 4 novembre 2024



=== Version 1.37

Cette version de classification BlueXP  inclut les mises à jour suivantes.

.Prise en charge de RHEL 8.10
Cette version prend en charge Red Hat Enterprise Linux v8.10 en plus des versions précédemment prises en charge. Cela s'applique à toute installation manuelle sur site de la classification BlueXP , y compris les déploiements de sites invisibles.

Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP  version 1.30 ou ultérieure : Red Hat Enterprise Linux version 8.8, 8.10, 9.0, 9.1, 9.2, 9.3 et 9.4.

En savoir plus sur https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Classification BlueXP"].

.Prise en charge de NFS v4.1
Cette version assure la prise en charge de NFS v4.1 en plus des versions précédemment prises en charge.

En savoir plus sur https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Classification BlueXP"].



== 10 octobre 2024



=== Version 1.36

.Prise en charge de RHEL 9.4
Cette version prend en charge Red Hat Enterprise Linux v9.4 en plus des versions précédemment prises en charge. Cela s'applique à toute installation manuelle sur site de la classification BlueXP , y compris les déploiements de sites invisibles.

Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP  version 1.30 ou ultérieure : Red Hat Enterprise Linux version 8.8, 9.0, 9.1, 9.2, 9.3 et 9.4.

En savoir plus sur https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["Présentation des déploiements de classifications BlueXP"].

.Amélioration des performances de numérisation
Cette version offre des performances de numérisation améliorées.



== 2 septembre 2024



=== Version 1.35

.Analyser les données StorageGRID
La classification BlueXP  peut maintenant analyser les données dans StorageGRID.

Pour plus de détails, reportez-vous à link:task-scanning-storagegrid.html["Analyser les données StorageGRID"].



== 5 août 2024



=== Version 1.34

Cette version de classification BlueXP  inclut la mise à jour suivante.

.Passez de CentOS à Ubuntu
La classification BlueXP  a mis à jour son système d'exploitation Linux pour Microsoft Azure et Google Cloud Platform (GCP) de CentOS 7.9 à Ubuntu 22.04.

Pour plus de détails sur le déploiement, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#prepare-the-linux-host-system["Installez sur un hôte Linux avec accès Internet et préparez le système hôte Linux"].



== 1er juillet 2024



=== Version 1.33

.Ubuntu pris en charge
Cette version prend en charge la plate-forme Linux Ubuntu 24.04.

.Les analyses de mappage rassemblent les métadonnées
Les métadonnées suivantes sont extraites des fichiers lors des analyses de mappage et sont affichées dans les tableaux de bord gouvernance, conformité et investigation :

* Environnement de travail
* Type d'environnement de travail
* Référentiel de stockage
* Type de fichier
* Capacité utilisée
* Nombre de fichiers
* Taille du fichier
* Création de fichier
* Dernier accès au fichier
* Dernier fichier modifié
* Heure de découverte du fichier
* Extraction des autorisations


.Données supplémentaires dans les tableaux de bord
Cette version met à jour les données qui apparaissent dans les tableaux de bord gouvernance, conformité et investigation lors des analyses de mappage.

Pour plus de détails, voir link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Quelle est la différence entre les analyses de cartographie et de classification"].



== 5 juin 2024



=== Version 1.32

.Nouvelle colonne État de mappage de la page Configuration
Cette version affiche désormais une nouvelle colonne d'état de mappage dans la page Configuration. La nouvelle colonne vous permet d'identifier si le mappage est en cours d'exécution, en file d'attente, en pause ou plus.

Pour plus d'informations sur les États, reportez-vous à la section https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html["Modifier les paramètres de numérisation"].



== 15 mai 2024



=== Version 1.31

.La classification est disponible en tant que service principal dans BlueXP
La classification BlueXP est désormais disponible en tant que fonctionnalité clé dans BlueXP, sans frais supplémentaires pour un maximum de 500 To de données numérisées. Aucune licence de classification ou abonnement payant n'est nécessaire. Alors que nous nous concentrons sur la fonctionnalité de classification BlueXP lors de l'analyse des systèmes de stockage NetApp avec cette nouvelle version, certaines fonctionnalités héritées ne seront disponibles que pour les clients qui avaient déjà payé pour une licence. L'utilisation de ces fonctions héritées expirera lorsque le contrat payé atteindra sa date de fin.

link:reference-free-paid.html["En savoir plus sur les fonctionnalités obsolètes"].



== 1er avril 2024



=== Version 1.30

.Prise en charge de la classification BlueXP RHEL v8.8 et v9.3
Cette version prend en charge Red Hat Enterprise Linux v8.8 et v9.3 en plus de la version 9.x précédemment prise en charge, qui nécessite Podman, plutôt que le moteur Docker. Cela s'applique à toute installation manuelle sur site de la classification BlueXP.

Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP version 1.30 ou supérieure : Red Hat Enterprise Linux version 8.8, 9.0, 9.1, 9.2 et 9.3.

En savoir plus sur https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["Présentation des déploiements de classifications BlueXP"].

La classification BlueXP est prise en charge si vous installez le connecteur sur un hôte RHEL 8 ou 9 résidant sur site. Elle n'est pas prise en charge si l'hôte RHEL 8 ou 9 réside dans AWS, Azure ou Google Cloud.

.Option d'activation de la collection de journaux d'audit supprimée
L'option permettant d'activer la collecte des journaux d'audit a été désactivée.

.Vitesse de numérisation améliorée
Les performances de numérisation sur les nœuds de scanner secondaires ont été améliorées. Vous pouvez ajouter d'autres nœuds de scanner si vous avez besoin d'une puissance de traitement supplémentaire pour vos numérisations. Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Installez la classification BlueXP sur un hôte disposant d'un accès Internet"].

.Mises à niveau automatiques
Si vous avez déployé la classification BlueXP sur un système disposant d'un accès Internet, le système est automatiquement mis à niveau. Auparavant, la mise à niveau s'est produite après un temps spécifique écoulé depuis la dernière activité de l'utilisateur. Avec cette version, la classification BlueXP est mise à niveau automatiquement si l'heure locale est comprise entre 1:00 AM et 5:00 AM. Si l'heure locale est en dehors de ces heures, la mise à niveau se produit après un délai spécifique écoulé depuis la dernière activité de l'utilisateur. Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Installez sur un hôte Linux avec accès à Internet"].

Si vous avez déployé la classification BlueXP sans accès à Internet, vous devez effectuer une mise à niveau manuelle. Pour plus de détails, reportez-vous à https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-dark-site.html["Installez la classification BlueXP sur un hôte Linux sans accès Internet"].



== 4 mars 2024



=== Version 1.29

.Vous pouvez maintenant exclure les données de numérisation qui résident dans certains répertoires de sources de données
Si vous souhaitez que la classification BlueXP exclut les données d'analyse qui résident dans certains répertoires de sources de données, vous pouvez ajouter ces noms de répertoires à un fichier de configuration traité par la classification BlueXP. Cette fonction vous permet d'éviter d'analyser des répertoires qui ne sont pas nécessaires ou qui pourraient renvoyer de faux résultats positifs pour les données personnelles.

https://docs.netapp.com/us-en/bluexp-classification/task-exclude-scan-paths.html["En savoir plus >>"].

.La prise en charge des instances extra-volumineuses est désormais qualifiée
Si vous avez besoin de la classification BlueXP pour analyser plus de 250 millions de fichiers, vous pouvez utiliser une très grande instance dans votre déploiement cloud ou votre installation sur site. Ce type de système peut analyser jusqu'à 500 millions de fichiers.

https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["En savoir plus >>"].



== 10 janvier 2024



=== Version 1.27

.Les résultats de la page d'enquête affichent désormais la taille totale en plus du nombre total d'éléments
Les résultats filtrés de la page Investigation affichent désormais la taille totale des éléments en plus du nombre total de fichiers. Cela peut vous aider lors du déplacement de fichiers, de la suppression de fichiers, etc.

.Configurer des ID de groupe supplémentaires comme « ouvert à l'entreprise »
Vous pouvez désormais configurer les ID de groupe dans NFS pour qu'ils soient considérés comme « ouverts à l'entreprise » directement dans la classification BlueXP si le groupe n'avait pas été défini initialement avec cette autorisation. Tous les fichiers et dossiers auxquels ces ID de groupe sont joints s'affichent comme « Ouvrir à l'organisation » dans la page Détails de l'enquête. Découvrez comment https://docs.netapp.com/us-en/bluexp-classification/task-add-group-id-as-open.html["Ajouter des ID de groupe supplémentaires comme « ouvert à l'organisation »"].



== 14 décembre 2023



=== Version 1.26.6

Cette version comprend quelques améliorations mineures.

La version a également supprimé les options suivantes :

* L'option permettant d'activer la collecte des journaux d'audit a été désactivée.
* Lors de l'enquête répertoires, l'option permettant de calculer le nombre de données d'informations personnelles identifiables (PII) par répertoires n'est pas disponible. Reportez-vous à la link:task-investigate-data.html["Examinez les données stockées dans votre organisation"].
* L'option d'intégration des données à l'aide d'étiquettes Azure information protection (AIP) a été désactivée. Reportez-vous à la section link:task-org-private-data.html["Organisez vos données privées"].




== 6 novembre 2023



=== Version 1.26.3

Les problèmes suivants ont été résolus dans cette version

* Correction d'une incohérence lors de la présentation du nombre de fichiers analysés par le système dans les tableaux de bord.
* Amélioration du comportement de numérisation en gérant et en signalant les fichiers et répertoires avec des caractères spéciaux dans le nom et les métadonnées.




== 4 octobre 2023



=== Version 1.26

.Prise en charge des installations sur site de la classification BlueXP sur RHEL version 9
Les versions 8 et 9 de Red Hat Enterprise Linux ne prennent pas en charge le moteur Docker requis pour l'installation de classification BlueXP. Nous prenons désormais en charge l'installation de classification BlueXP sur RHEL 9.0, 9.1 et 9.2 en utilisant Podman version 4 ou ultérieure comme infrastructure de conteneur. Si votre environnement requiert l'utilisation des dernières versions de RHEL, vous pouvez désormais installer la classification BlueXP (version 1.26 ou supérieure) lorsque vous utilisez Podman.

À l'heure actuelle, nous ne prenons pas en charge les installations de sites invisibles ou les environnements de numérisation distribués (à l'aide d'un scanner maître et distant) lors de l'utilisation de RHEL 9.x.



== 5 septembre 2023



=== Version 1.25

.Petits et moyens déploiements temporairement indisponibles
Lorsque vous déployez une instance de classification BlueXP dans AWS, l'option de sélectionner *Deploy > Configuration* et de choisir une instance de petite ou moyenne taille n'est pas disponible pour le moment. Vous pouvez toujours déployer l'instance à l'aide de la grande taille d'instance en sélectionnant *déployer > déployer*.

.Appliquez des balises sur un maximum de 100,000 éléments à partir de la page Résultats d'enquête
Dans le passé, vous ne pouviez appliquer des balises qu'à une seule page à la fois dans la page Résultats d'enquête (20 éléments). Vous pouvez maintenant sélectionner *tous* éléments dans les pages Résultats d'enquête et appliquer des balises à tous les éléments - jusqu'à 100,000 éléments à la fois. https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assign-tags-to-files["Découvrez comment"].

.Identifiez les fichiers dupliqués avec une taille de fichier minimale de 1 Mo
Classification BlueXP utilisée pour identifier les fichiers dupliqués uniquement lorsque les fichiers étaient de 50 Mo ou plus. Désormais, les fichiers dupliqués commençant par 1 Mo peuvent être identifiés. Vous pouvez utiliser les filtres de la page Investigation « taille du fichier » ainsi que « doublons » pour voir quels fichiers d'une certaine taille sont dupliqués dans votre environnement.



== 17 juillet 2023



=== Version 1.24

.Deux nouveaux types de données personnelles allemandes sont identifiés par la classification BlueXP
La classification BlueXP peut identifier et catégoriser les fichiers qui contiennent les types de données suivants :

* ID allemand (Personalausweisnummer)
* Numéro de sécurité sociale allemand (Sozialversicherungsnummer)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["Consultez tous les types de données personnelles que la classification BlueXP peut identifier dans vos données"].

.La classification BlueXP est entièrement prise en charge en mode restreint et en mode privé
La classification BlueXP est désormais entièrement prise en charge sur les sites sans accès Internet (mode privé) et avec un accès Internet sortant limité (mode restreint). https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["En savoir plus sur les modes de déploiement BlueXP pour Connector"^].

.Possibilité d'ignorer les versions lors de la mise à niveau d'une installation en mode privé de la classification BlueXP
Vous pouvez maintenant effectuer la mise à niveau vers une version plus récente de la classification BlueXP, même s'il n'est pas séquentiel. Cela signifie que la limitation actuelle de la mise à niveau de la classification BlueXP par une version à la fois n'est plus nécessaire. Cette fonction est pertinente à partir de la version 1.24.

.L'API de classification BlueXP est disponible
L'API de classification BlueXP vous permet d'effectuer des actions, de créer des requêtes et d'exporter des informations sur les données que vous analysez. La documentation interactive est disponible à l'aide de swagger. La documentation est divisée en plusieurs catégories, notamment Investigation, Compliance, Governance et Configuration. Chaque catégorie fait référence aux onglets de l'interface de classification BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["En savoir plus sur les API de classification BlueXP"].



== 6 juin 2023



=== Version 1.23

.Le japonais est désormais pris en charge lors de la recherche de noms de sujet de données
Les noms japonais peuvent maintenant être saisis lors de la recherche du nom d'un sujet en réponse à une demande d'accès de la personne concernée (DSAR, Data Subject Access Request). Vous pouvez générer un https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html["Rapport de demande d'accès au sujet des données"] avec les informations obtenues. Vous pouvez également saisir des noms japonais dans le https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Filtre « sujet des données » dans la page enquête sur les données"] pour identifier les fichiers contenant le nom du sujet.

.Ubuntu est maintenant une distribution Linux prise en charge sur laquelle vous pouvez installer la classification BlueXP
Ubuntu 22.04 a été qualifié comme système d'exploitation pris en charge pour la classification BlueXP. Vous pouvez installer la classification BlueXP sur un hôte Ubuntu Linux de votre réseau ou sur un hôte Linux dans le cloud en utilisant la version 1.23 du programme d'installation. https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["Découvrez comment installer la classification BlueXP sur un hôte avec Ubuntu installé"].

.Red Hat Enterprise Linux 8.6 et 8.7 ne sont plus pris en charge par les nouvelles installations de classification BlueXP
Ces versions ne sont pas prises en charge par les nouveaux déploiements, car Red Hat ne prend plus en charge Docker, ce qui est un prérequis. Si vous disposez d'un ordinateur de classification BlueXP sous RHEL 8.6 ou 8.7, NetApp continuera à prendre en charge votre configuration.

.La classification BlueXP peut être configurée en tant que collecteur FPolicy pour recevoir les événements FPolicy des systèmes ONTAP
Vous pouvez activer la collecte des journaux d'audit de l'accès aux fichiers sur votre système de classification BlueXP pour les événements d'accès aux fichiers détectés sur les volumes de vos environnements de travail. La classification BlueXP peut capturer les types d'événements FPolicy suivants et les utilisateurs qui ont effectué les actions sur vos fichiers : créer, lire, écrire, supprimer, renommer, Modifiez le propriétaire/les autorisations et modifiez SACL/DACL.

.Les licences Data Sense BYOL sont désormais prises en charge sur les sites invisibles
Vous pouvez désormais charger votre licence Data Sense BYOL dans le portefeuille digital BlueXP situé dans un site invisible pour que vous soyez averti lorsque le niveau de licence est faible.



== 3 avril 2023



=== Version 1.22

.Nouveau rapport d'évaluation de découverte de données
Le rapport d'évaluation de la découverte de données fournit une analyse de haut niveau de votre environnement analysé afin de mettre en évidence les résultats du système et de montrer les points préoccupants et les étapes de correction potentielles. L'objectif de ce rapport est de sensibiliser les clients aux préoccupations liées à la gouvernance des données, à l'exposition aux risques en matière de sécurité des données et aux lacunes de conformité de leurs jeux de données. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["Découvrez comment générer et utiliser le rapport d'évaluation de découverte de données"].

.Possibilité de déployer la classification BlueXP sur des instances plus petites dans le cloud
Lors du déploiement de la classification BlueXP à partir d'un connecteur BlueXP dans un environnement AWS, vous pouvez désormais choisir entre deux types d'instances plus petits que ceux disponibles avec l'instance par défaut. Si vous analysez un petit environnement, vous pouvez réduire vos coûts liés au cloud. Cependant, il existe des restrictions lors de l'utilisation de la plus petite instance. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Voir les types d'instances et les limites disponibles"].

.Un script autonome est désormais disponible pour qualifier votre système Linux avant l'installation de la classification BlueXP
Si vous souhaitez vérifier que votre système Linux répond à toutes les conditions préalables, indépendamment de l'installation de la classification BlueXP, vous pouvez télécharger un script distinct qui teste uniquement les prérequis. https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["Découvrez comment vérifier si votre hôte Linux est prêt à installer la classification BlueXP"].



== 7 mars 2023



=== Version 1.21

.Nouvelle fonctionnalité permettant d'ajouter vos propres catégories personnalisées à partir de l'interface de classification BlueXP
La classification BlueXP vous permet désormais d'ajouter vos propres catégories personnalisées afin que la classification BlueXP identifie les fichiers qui s'intègrent dans ces catégories. La classification BlueXP  comporte de nombreux https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["catégories prédéfinies"], de sorte que cette fonction vous permet d'ajouter des catégories personnalisées afin d'identifier où les informations propres à votre organisation se trouvent dans vos données.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["En savoir plus >>"^].

.Vous pouvez désormais ajouter des mots-clés personnalisés à partir de l'interface de classification BlueXP
La classification BlueXP a eu la possibilité d'ajouter des mots-clés personnalisés que la classification BlueXP identifiera pendant un certain temps lors des analyses futures. Toutefois, vous avez dû vous connecter à l'hôte de classification BlueXP Linux et utiliser une interface de ligne de commande pour ajouter des mots-clés. Dans cette version, l'ajout de mots-clés personnalisés se fait dans l'interface de classification BlueXP, ce qui facilite considérablement l'ajout et la modification de ces mots-clés.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["En savoir plus sur l'ajout de mots-clés personnalisés à partir de l'interface de classification BlueXP"^].

.Possibilité de disposer de fichiers de classification BlueXP *NOT* lors de la modification de l'« heure du dernier accès »
Par défaut, si la classification BlueXP ne dispose pas des autorisations d'écriture adéquates, le système ne scrutera pas les fichiers de vos volumes, car la classification BlueXP ne peut pas rétablir l'heure du dernier accès à l'horodatage d'origine. Cependant, si vous ne vous souciez pas de savoir si l'heure du dernier accès est réinitialisée à l'heure d'origine dans vos fichiers, vous pouvez remplacer ce comportement dans la page Configuration afin que la classification BlueXP analyse les volumes indépendamment des autorisations.

Grâce à cette fonctionnalité, et un nouveau filtre nommé « événement d'analyse » a été ajouté. Vous pouvez ainsi afficher les fichiers non classifiés, car la classification BlueXP n'a pas pu rétablir l'heure du dernier accès, ou les fichiers classés même si la classification BlueXP n'a pas pu rétablir l'heure du dernier accès.

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html["En savoir plus sur l'horodatage du dernier accès et les autorisations requises par la classification BlueXP"].

.Trois nouveaux types de données personnelles sont identifiés par la classification BlueXP
La classification BlueXP peut identifier et catégoriser les fichiers qui contiennent les types de données suivants :

* Numéro de carte d'identité Botswana (Omang)
* Botswana Numéro de passeport
* Carte d'identité nationale d'enregistrement de Singapour (NRIC)


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Consultez tous les types de données personnelles que la classification BlueXP peut identifier dans vos données"].

.Mise à jour des fonctionnalités des répertoires
* L'option « Rapport CSV léger » pour les rapports d'investigation de données inclut désormais des informations provenant des répertoires.
* Le filtre heure « dernier accès » affiche désormais l'heure du dernier accès pour les fichiers et les répertoires.


.Améliorations apportées à l'installation
* Le programme d'installation de classification BlueXP pour les sites sans accès à Internet (sites invisibles) effectue désormais un pré-contrôle pour s'assurer que vos exigences système et réseau sont en place pour une installation réussie.
* Les fichiers journaux d'audit d'installation sont enregistrés maintenant ; ils sont écrits dans `/ops/netapp/install_logs`.




== 5 février 2023



=== Version 1.20

.Possibilité d'envoyer des e-mails de notification basés sur des règles à n'importe quelle adresse e-mail
Dans les versions précédentes de la classification BlueXP, vous pouviez envoyer des alertes par e-mail aux utilisateurs BlueXP de votre compte lorsque certaines stratégies stratégiques renvoient des résultats. Cette fonction vous permet d'obtenir des notifications pour protéger vos données lorsque vous n'êtes pas en ligne. Vous pouvez désormais envoyer des alertes par e-mail à partir de stratégies à tous les autres utilisateurs - jusqu'à 20 adresses e-mail - qui ne sont pas dans votre compte BlueXP.

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["En savoir plus sur l'envoi d'alertes par e-mail basées sur les résultats des règles"].

.Vous pouvez désormais ajouter des modèles personnels à partir de l'interface de classification BlueXP
La classification BlueXP a eu la possibilité d'ajouter des « données personnelles » personnalisées que la classification BlueXP identifiera lors des analyses futures pendant un certain temps. Cependant, vous avez dû vous connecter à l'hôte de classification BlueXP Linux et utiliser une ligne de commande pour ajouter les modèles personnalisés. Dans cette version, l'ajout de modèles personnels à l'aide d'un regex se fait dans l'interface de classification de BlueXP, ce qui facilite considérablement l'ajout et la modification de ces modèles personnalisés.

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["En savoir plus sur l'ajout de modèles personnalisés à partir de l'interface de classification BlueXP"^].

.Possibilité de déplacer 15 millions de fichiers à l'aide de la classification BlueXP
Par le passé, vous pouviez déplacer jusqu'à 100,000 fichiers source vers n'importe quel partage NFS grâce à la classification BlueXP. Vous pouvez désormais déplacer jusqu'à 15 millions de fichiers simultanément. https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html["En savoir plus sur le déplacement des fichiers source à l'aide de la classification BlueXP"].

.Possibilité de voir le nombre d'utilisateurs ayant accès aux fichiers SharePoint Online
Le filtre « nombre d'utilisateurs avec accès » prend désormais en charge les fichiers stockés dans les référentiels SharePoint Online. Auparavant, seuls les fichiers stockés sur des partages CIFS étaient pris en charge. Notez que les groupes SharePoint qui ne sont pas actifs basés sur un répertoire ne seront pas pris en compte dans ce filtre à l'heure actuelle.

.Le nouvel état « réussite partielle » a été ajouté au panneau État de l'action
Le nouvel état « réussite partielle » indique qu'une action de classification BlueXP est terminée, que certains éléments ont échoué et que certains éléments ont réussi, par exemple, lorsque vous déplacez ou supprimez des fichiers 100. De plus, le statut « terminé » a été renommé « succès ». Par le passé, l'état « terminé » peut lister les actions qui ont réussi et qui ont échoué. Désormais, le statut « réussite » signifie que toutes les actions ont réussi sur tous les éléments. https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["Voir comment afficher le panneau Etat des actions"].



== 9 janvier 2023



=== Version 1.19

.Possibilité d'afficher un graphique de fichiers contenant des données sensibles et qui sont trop permissives
Le tableau de bord gouvernance a ajouté une nouvelle zone données et autorisations larges_ qui fournit une carte thermique de fichiers contenant des données sensibles (y compris des données personnelles sensibles et sensibles) et qui sont trop permissives. Ainsi, vous pouvez identifier les risques potentiels liés aux données sensibles. https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["En savoir plus >>"].

.Trois nouveaux filtres sont disponibles dans la page Data Investigation
De nouveaux filtres sont disponibles pour affiner les résultats affichés dans la page recherche de données :

* Le filtre « nombre d'utilisateurs avec accès » indique quels fichiers et dossiers sont ouverts à un certain nombre d'utilisateurs. Vous pouvez choisir une plage de nombres pour affiner les résultats, par exemple pour voir quels fichiers sont accessibles par 51-100 utilisateurs.
* Les filtres « heure créée », « heure découverte », « dernière modification » et « dernier accès » vous permettent désormais de créer une plage de dates personnalisée au lieu de sélectionner une plage de jours prédéfinie. Par exemple, vous pouvez rechercher des fichiers avec une "heure de création" "plus de 6 mois", ou avec une "date de dernière modification" dans les "10 derniers jours".
* Le filtre "chemin du fichier" vous permet maintenant de spécifier les chemins que vous souhaitez exclure des résultats de la requête filtrée. Si vous entrez des chemins pour inclure et exclure certaines données, la classification BlueXP recherche d'abord tous les fichiers des chemins inclus, puis supprime les fichiers des chemins exclus, puis affiche les résultats.


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Voir la liste de tous les filtres que vous pouvez utiliser pour examiner vos données"].

.La classification BlueXP peut identifier le numéro individuel japonais
La classification BlueXP peut identifier et catégoriser les fichiers qui contiennent le numéro individuel japonais (également appelé mon numéro). Cela inclut le numéro personnel et le numéro personnel de l'entreprise. https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["Consultez tous les types de données personnelles que la classification BlueXP peut identifier dans vos données"].
