= Version 1.39
:allow-uri-read: 




=== Version 1.39

Cette version de classification BlueXP  met à jour le processus d'exportation du rapport d'investigation de données. Cette mise à jour d'exportation est utile pour effectuer des analyses supplémentaires sur vos données, créer des visualisations supplémentaires sur les données ou partager les résultats de votre enquête de données avec d'autres personnes.

Auparavant, l'exportation du rapport d'investigation de données était limitée à 10,000 lignes. Avec cette version, la limite a été supprimée afin que vous puissiez exporter toutes vos données. Cette modification vous permet d'exporter davantage de données à partir de vos rapports d'investigation de données, vous offrant ainsi une plus grande flexibilité dans votre analyse de données.

Vous pouvez choisir l'environnement de travail, les volumes, le dossier de destination et le format JSON ou CSV. Le nom de fichier exporté inclut un horodatage qui vous aide à identifier le moment où les données ont été exportées.

Les environnements de travail pris en charge sont les suivants :

* Cloud Volumes ONTAP
* FSX pour ONTAP
* ONTAP
* Partager le groupe


L'exportation de données à partir du rapport d'investigation de données comporte les limites suivantes :

* Le nombre maximum d'enregistrements à télécharger est de 500 millions. Par type (fichiers, répertoires et tables)
* L'exportation d'un million de documents devrait prendre environ 35 minutes.


Pour plus de détails sur l'investigation des données et le rapport, voir https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Analysez les données stockées dans votre entreprise"].
