= Version 1.40
:allow-uri-read: 




=== Version 1.40

Cette version de classification BlueXP  inclut les mises à jour suivantes.

.Prise en charge de RHEL 9.5
Cette version prend en charge Red Hat Enterprise Linux v9.5 en plus des versions précédemment prises en charge. Cela s'applique à toute installation manuelle sur site de la classification BlueXP , y compris les déploiements de sites invisibles.

Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP  version 1.30 ou ultérieure : Red Hat Enterprise Linux version 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 et 9.5.

.Hiérarchiser les acquisitions
Lors de la configuration de la numérisation, vous pouvez hiérarchiser les acquisitions les plus importantes afin qu'elles soient effectuées avant d'autres acquisitions. Cette fonction vous aide lorsque vous avez de nombreux environnements de travail et que vous voulez vous assurer que les numérisations à priorité élevée sont effectuées avec succès au début.

Il existe deux types d'acquisitions :

* *Les analyses cartographiques uniquement* fournissent uniquement une vue d'ensemble de haut niveau de vos données. Le mappage peut être effectué très rapidement sur vos sources de données car il n'accède pas aux fichiers pour voir les données à l'intérieur.
* *Les analyses Map et Classify* permettent une analyse approfondie de vos données.


Les analyses de mappage uniquement permettent d'analyser rapidement vos données pour identifier les sources de données nécessitant davantage de recherche, puis d'activer par la suite les analyses de mappage et de classification uniquement sur les sources ou volumes de données requis.

La priorité est attribuée uniquement aux acquisitions de mappage uniquement, et non aux acquisitions de mappage et de classification.

La priorité est définie sur 1 par défaut et vous pouvez la remplacer par un nombre compris entre 1 et 10. Plus le nombre est faible, plus la priorité est élevée. Si vous ne définissez pas de priorité, une priorité de 5 est attribuée à l'analyse.

Pour modifier la priorité, procédez comme suit :

. Dans le menu BlueXP  Classification, sélectionnez *Configuration*.
. Sélectionnez les ressources à hiérarchiser.
. Dans l'option actions ..., sélectionnez *hiérarchiser l'acquisition*.


.Réessayer les numérisations
Avec cette version, vous pouvez réessayer les analyses qui ont échoué. Cette fonction est utile lorsque vous avez échoué à une analyse en raison d'un problème temporaire, tel qu'une panne de réseau. Vous pouvez réessayer la numérisation sans avoir à la reconfigurer.

Pour réessayer une numérisation, procédez comme suit :

. Dans le menu BlueXP  Classification, sélectionnez *Configuration*.
. Effectuez l'une des opérations suivantes :
+
** Pour réessayer toutes les acquisitions ayant échoué, sélectionnez *Réessayer toutes les acquisitions*.
** Pour réessayer une analyse spécifique, sélectionnez la ressource et sélectionnez *Réessayer l'analyse* dans l'option actions ....




La numérisation est relancée avec la même configuration que la numérisation d'origine. Si la numérisation échoue à nouveau, vous pouvez la réessayer autant de fois que nécessaire.
