= Version 1.40
:allow-uri-read: 




=== Version 1.40

Cette version de classification BlueXP  inclut les mises à jour suivantes.

.Prise en charge de RHEL 9.5
Cette version prend en charge Red Hat Enterprise Linux v9.5 en plus des versions précédemment prises en charge. Cela s'applique à toute installation manuelle sur site de la classification BlueXP , y compris les déploiements de sites invisibles.

Les systèmes d'exploitation suivants nécessitent l'utilisation du moteur de conteneur Podman et requièrent la classification BlueXP  version 1.30 ou ultérieure : Red Hat Enterprise Linux version 8.8, 8.10, 9.0, 9.1, 9.2, 9.3, 9.4 et 9.5.

.Prioriser les acquisitions de mappage uniquement
Lorsque vous effectuez des acquisitions de mappage uniquement, vous pouvez hiérarchiser les acquisitions les plus importantes. Cette fonction vous aide lorsque vous disposez de nombreux environnements de travail et que vous souhaitez vous assurer que les numérisations à haute priorité sont effectuées en premier.

Par défaut, les analyses sont mises en file d'attente en fonction de l'ordre dans lequel elles sont initiées. Avec la possibilité de hiérarchiser les numérisations, vous pouvez déplacer les numérisations vers l'avant de la file d'attente. Plusieurs acquisitions peuvent être classées par ordre de priorité. La priorité est désignée dans un ordre de premier entrée et de premier sortie, ce qui signifie que la première analyse prioritaire se déplace vers l'avant de la file d'attente ; la deuxième analyse prioritaire devient la deuxième dans la file d'attente, etc.

La priorité est accordée une fois. Les nouvelles analyses automatiques des données de mappage sont effectuées dans l'ordre par défaut.

La priorisation est limitée à link:concept-cloud-compliance.html["analyses de mappage uniquement"]; elle n'est pas disponible pour les acquisitions de cartes et de classification.

Pour plus d'informations, voir link:task-managing-repo-scanning.html#prioritize-scans["Hiérarchiser les acquisitions"].

.Réessayez toutes les acquisitions
La classification BlueXP  prend en charge la possibilité de répéter par lots toutes les acquisitions ayant échoué.

Vous pouvez relancer des acquisitions en mode batch avec la fonction **Réessayer tout**. Si les analyses de classification échouent en raison d'un problème temporaire, tel qu'une panne réseau, vous pouvez réessayer toutes les analyses en même temps à l'aide d'un seul bouton au lieu de les essayer à nouveau individuellement. Les acquisitions peuvent être relancées autant de fois que nécessaire.

Pour réessayer toutes les acquisitions :

. Dans le menu BlueXP  Classification, sélectionnez *Configuration*.
. Pour réessayer toutes les acquisitions ayant échoué, sélectionnez *Réessayer toutes les acquisitions*.


.Amélioration de la précision du modèle de catégorisation
La précision du modèle de machine learning du link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["catégories prédéfinies"] a augmenté de 11 %.
